#!/bin/bash
set -e

NBANDS="17"
SP_ID="trappist1e"

echo "Started mk_sp_lw_${NBANDS}_${SP_ID}: $(date)"

. ./env_trappist1e

if [ $RAD_BIN ] ; then
  echo "Using SOCRATES binaries in: $RAD_BIN"
else
  echo "Path to SOCRATES binaries not set. Check env_trappist1e."
  exit 1
fi

# 1. Create skeleton spectral file
SKEL_FILE="sp_lw_${NBANDS}_${SP_ID}_skel"
echo ">>> Creating skeleton: $SKEL_FILE"

bash mk_sp_lw_17_trappist_skel

# 2. Create directories for coefficients
K_DIR="${LW_DATA}/k_coeffs"
mkdir -p "$K_DIR"

procs=10

echo ">>> Calculating k-coefficients..."

# --- CO2 Lines ---
if [ ! -s ${K_DIR}/co2_l ] ; then
  echo "  - CO2 Lines"
  rm -f ${K_DIR}/co2_l ${K_DIR}/co2_lm ${CO2_LBL_LW}
  Ccorr_k -F ${PT_FILE} -D ${HITRAN_CO2} \
    -lo 2 -R 1 ${NBANDS} -c 10000.0 -i 0.1 -l 2 ${COL_CO2} \
    -t 1.0e-3 -s ${SKEL_FILE} +p -lk -np $procs \
    -sb gas_fractions -lp 2 \
    -o ${K_DIR}/co2_l -m ${K_DIR}/co2_lm -L ${CO2_LBL_LW} \
    > ${K_DIR}/co2_log 2>&1
fi

# --- H2O Lines ---
if [ ! -s ${K_DIR}/h2o_l ] ; then
  echo "  - H2O Lines"
  rm -f ${K_DIR}/h2o_l ${K_DIR}/h2o_lm ${K_DIR}/h2o_map.nc ${H2O_LBL_LWF}
  Ccorr_k -F ${PT_FILE} -D ${HITRAN_H2O} \
    -lo 1 -R 1 ${NBANDS} -c 2500.0 -i 0.1 -l 1 ${COL_H2O} \
    -t 1.0e-3 -s ${SKEL_FILE} +p -lk -np $procs \
    -k -x ${CONT_H2O_FRN} \
    -o ${K_DIR}/h2o_l -m ${K_DIR}/h2o_lm -L ${H2O_LBL_LWF} \
    -sm ${K_DIR}/h2o_map.nc \
    > ${K_DIR}/h2o_log 2>&1
fi

# --- H2O Self-Broadened Continuum (Elsey-Shine) ---
if [ ! -s ${K_DIR}/h2o-h2o_c ] ; then
  echo "  - H2O Self-Continuum"
  rm -f ${K_DIR}/h2o-h2o_c ${K_DIR}/h2o-h2o_cm ${H2O_H2O_LBL_LW}
  Ccorr_k -F ${CONT_PT_FILE} \
    -R 1 ${NBANDS} -c 2500.0 -i 0.1 \
    -ct 1 1 ${CIA_H2O_H2O} -t 1.0e-3 \
    -e ${CONT_H2O_S296} ${CONT_H2O_S260} \
    -k -s ${SKEL_FILE} +p -lk -np $procs \
    -o ${K_DIR}/h2o-h2o_c -m ${K_DIR}/h2o-h2o_cm \
    -lw ${K_DIR}/h2o_map.nc -L ${H2O_H2O_LBL_LW} \
     > ${K_DIR}/h2o-h2o_clog 2>&1
fi

# --- CO2-CO2 CIA ---
if [ ! -s ${K_DIR}/co2-co2_c ] ; then
  echo "  - CO2-CO2 CIA"
  rm -f ${K_DIR}/co2-co2_c ${K_DIR}/co2-co2_cm ${CO2_CO2_LBL_LW}
  Ccorr_k -F ${CONT_PT_FILE} -CIA ${CONT_CO2_CO2} \
    -R 1 ${NBANDS} -c 2500.0 -i 1.0 \
    -ct 2 2 ${CIA_CO2_CO2} -t 1.0e-3 \
    -k -s ${SKEL_FILE} +p -lk -np $procs \
    -o ${K_DIR}/co2-co2_c -m ${K_DIR}/co2-co2_cm \
    -L ${CO2_CO2_LBL_LW} \
     > ${K_DIR}/co2-co2_clog 2>&1
fi

# --- N2-N2 CIA ---
if [ ! -s ${K_DIR}/n2-n2_c ] ; then
  echo "  - N2-N2 CIA"
  rm -f ${K_DIR}/n2-n2_c ${K_DIR}/n2-n2_cm ${N2_N2_LBL_LW}
  Ccorr_k -F ${CONT_PT_FILE} -CIA ${CONT_N2_N2} \
    -R 1 ${NBANDS} -c 2500.0 -i 1.0 \
    -ct 13 13 ${CIA_N2_N2} -t 1.0e-3 \
    -k -s ${SKEL_FILE} +p -lk -np $procs \
    -o ${K_DIR}/n2-n2_c -m ${K_DIR}/n2-n2_cm \
    -L ${N2_N2_LBL_LW} \
     > ${K_DIR}/n2-n2_clog 2>&1
fi

echo ">>> Calculating cloud optical properties..."
CLD_DIR="${LW_DATA}/cloud_coeffs"
mkdir -p "$CLD_DIR"

if [ ! -s ${CLD_DIR}/fit_lw_drop5 ] ; then
  echo "  - Droplets (Type 5)"
  Cscatter_average -s ${SKEL_FILE} -P 1 -t -p 250 \
    -f 5 ${CLD_DIR}/fit_lw_drop5 \
    ${CLD_DIR}/mon_lw_drop5 1.e3 \
    ${RAD_DATA}/cloud/scatter_drop_type5 > /dev/null 2>&1
fi

if [ ! -s ${CLD_DIR}/fit_lw_ice8 ] ; then
  echo "  - Ice (Type 8)"
  Cscatter_average -s ${SKEL_FILE} -P 1 -w -p 250 \
    -f 12 ${CLD_DIR}/fit_lw_ice8 \
    ${CLD_DIR}/mon_lw_ice8 920 \
    ${RAD_DATA}/cloud/scatter_ice_lw_type8 > /dev/null 2>&1
fi

echo ">>> Assembling Final Spectral File..."

FINAL_FILE="sp_lw_${NBANDS}_${SP_ID}"
rm -f ${FINAL_FILE} ${FINAL_FILE}_k

# Assembly sequence:
# Block 5: H2O lines, CO2 lines
# Block 19: H2O self-cont, CO2-CO2 CIA, N2-N2 CIA
# Block 10: Droplets
# Block 12: Ice crystals
# Block 6: Thermal source (60K - 540K)
prep_spec << EOF > mk_sp_lw_${NBANDS}_${SP_ID}_out 2>&1
${SKEL_FILE}
n
${FINAL_FILE}
5
${K_DIR}/h2o_l
5
y
${K_DIR}/co2_l
19
${K_DIR}/h2o-h2o_c
19
y
${K_DIR}/co2-co2_c
19
y
${K_DIR}/n2-n2_c
10
5
${CLD_DIR}/fit_lw_drop5
1.50000E-06 5.00000E-05
12
8
${CLD_DIR}/fit_lw_ice8
6
n
t
1 500
500
-1
EOF

echo "Finished mk_sp_lw_${NBANDS}_${SP_ID}: $(date)"
exit 0
