#! /bin/bash
#
# Script to run CDL to SAMSON conversion
#
touch $LOCK_FILE
INPUT=''
OUTFILE=''
BASE=''
#
# Process options
#
while [ $# -gt 0 ]
do case $1 in
      -o) OUTFILE=$2 ; shift 2 ;;
      -a) BASE=$2 ; shift 2 ;;
      -i) INPUT=$2 ; shift 2 ;;
      -*) echo "Invalid option" ; exit 1 ;;
      *) INPUT=$1 ; shift ;;
   esac
done

if [ "$BASE" ]
   then for FILE in ${BASE}.* 
   do 
cat > /tmp/cdl2samson.$$ << EOF
$FILE
samson_$FILE
EOF
cdl2samson  < /tmp/cdl2samson.$$ > /dev/null && echo "Written samson_$FILE"
rm -f /tmp/cdl2samson.$$
   done

else

if [ ! "$OUTFILE" ]
   then OUTFILE="samson_${INPUT}"
fi
cat > /tmp/cdl2samson.$$ << EOF
$INPUT
$OUTFILE
EOF
cdl2samson  < /tmp/cdl2samson.$$ > /dev/null && echo "Written $OUTFILE"
rm -f /tmp/cdl2samson.$$

fi

rm -f $LOCK_FILE
