#! /bin/bash
#
# Script to run the program to generate a surface field.
# This version works only with one point and basis function.
#
touch $LOCK_FILE
#
while [ $# -gt 0 ]
do case $1 in
      -o) OUTFILE=$2 ; shift 2 ;;
      -n) OUTNAME=$2 ; shift 2 ;;
      -L) OUTLONG=$2 ; shift 2 ;;
      -u) OUTUNIT=$2 ; shift 2 ;;
      -b) WEIGHTS=$2 ; N_BAS=1 ; shift 2 ;;
      -N) LONS=$2 ; N_LON=1 ; shift 2 ;;
      -T) LATS=$2 ; N_LAT=1 ; shift 2 ;;
       *) echo "Unsupported version of command.\n" ; exit 1 ;;
   esac
done
cat > /tmp/gsc.$$ << EOF
$N_LON
$N_LAT
$LONS
$LATS
$N_BAS
$WEIGHTS
$OUTFILE
$OUTNAME
$OUTUNIT
$OUTLONG
EOF
gen_surf_cdl < /tmp/gsc.$$ > /dev/null
rm -f /tmp/gsc.$$
rm -f $LOCK_FILE

