#! /bin/bash
#
# Script to run CDL/netCDF interpolation program
#
touch $LOCK_FILE
#
# Store the original positional parameters since they will be
# overwritten by set_param_mod.
#
ARG=$*
#
# Obtain Configured values of parameters
#
. $RAD_SCRIPT/set_param_mod interp_mode_pcf.f90
#
# Restore the original positional parameters.
#
set -- $ARG
#
#
# Process options
#
while [ $# -gt 0 ]
do case $1 in
      -g) GRID=$2 ; shift 2 ;;
      -o) OUTFILE=$2 ; shift 2 ;;
      -n) OUTNAME=$2 ; shift 2 ;;
      -u) OUTUNIT=$2 ; shift 2 ;;
      -L) OUTLONG=$2 ; shift 2 ;;
      -lnn) INTERPOLATE=$IP_1_LIN_LIN ; shift ;;
      -lgn) INTERPOLATE=$IP_1_LOG_LIN ; shift ;;
      -lng) INTERPOLATE=$IP_1_LIN_LOG ; shift ;;
      -lgg) INTERPOLATE=$IP_1_LOG_LOG ; shift ;;
      -cnn) INTERPOLATE=$IP_3_LIN_LIN ; shift ;;
      -cgn) INTERPOLATE=$IP_3_LOG_LIN ; shift ;;
      -cng) INTERPOLATE=$IP_3_LIN_LOG ; shift ;;
      -cgg) INTERPOLATE=$IP_3_LOG_LOG ; shift ;;
      -*) echo "Invalid option"; exit -1 ;;
      *) infile=$1 ; shift ;;
   esac
done
cat > /tmp/intp.$$ << EOF
$infile
$GRID
$INTERPOLATE
$OUTFILE
$OUTNAME
$OUTUNIT
$OUTLONG
EOF
ftype=`dd bs=3 count=1 if="$infile" 2> /dev/null`
if [ $ftype = "CDF" ]
   then interp_cdf < /tmp/intp.$$ > /dev/null
else
   interp < /tmp/intp.$$ > /dev/null
fi
rm -f /tmp/intp.$$
rm -f $LOCK_FILE
