#! /bin/bash
#
# Script to run program to integrate mixing ratios vertically.
#
touch $LOCK_FILE
while [ $# -gt 0 ]
do case $1 in
      -o) OUTPUT=$2 ; shift 2 ;;
       *) INPUT=$1 ; shift ;;
   esac
done
cat > /tmp/vi.$$ << EOF
$INPUT
$OUTPUT
EOF
( vert_int < /tmp/vi.$$ ) > /dev/null
rm -f /tmp/vi.$$
rm -f $LOCK_FILE
