#!/bin/bash

rm -f Css* Iss* fit_* mon_* sp_lw_10_titan* sp_sw_14_titan* convert 2>/dev/null
cc -o convert convert.c

for RE in 1.0 1.5 2.0 3.0 4.5 6.0 7.5 9.0 10.5 12.0 13.5 15.0 16.5 18.0 \
          20.0 22.0 24.0 26.0 28.0 30.0 33.0 36.0 39.0 42.0 46.0 50.0 55.0
do
  if [ ! -s Css${RE}_0.1 ] ; then
    ./scatter ${RE}
  fi
done

if [ -f scatter_drop_titan_type5 ] ; then rm -f scatter_drop_titan_type5 ; fi
for RE in 1.0 1.5 2.0 3.0 4.5 6.0 7.5 9.0 10.5 12.0 13.5 15.0 16.5 18.0 \
          20.0 22.0 24.0 26.0 28.0 30.0 33.0 36.0 39.0 42.0 46.0 50.0 55.0
do
   cat Css${RE}* >> scatter_drop_titan_type5
done

for RE in 24.0 26.0 28.0 30.0 33.0 36.0 39.0 42.0 46.0 50.0 55.0 60.0 70.0 80.0
do
  if [ ! -s Iss${RE}_0.1 ] ; then
    ./scatter_ice ${RE}
  fi
done

if [ -f scatter_ice_titan_type1 ] ; then rm -f scatter_ice_titan_type1 ; fi
for RE in 24.0 26.0 28.0 30.0 33.0 36.0 39.0 42.0 46.0 50.0 55.0 60.0 70.0 80.0
do
   cat Iss${RE}* >> scatter_ice_titan_type1
done

./scatter_average_titan
