#!/bin/bash

ierr=0
rm -f q*.txt q*.zip parsum_2021.dat molparam.txt

wget https://hitran.org/media/molparam.txt
wget https://hitran.org/data/Q/q_all_TIPS2021.zip
if [ -f q_all_TIPS2021.zip ] ; then
  unzip -q q_all_TIPS2021.zip
else
  echo 'TIPS data not accessible'
  exit 0
fi

qtxt2parsum
diff -q parsum_2021.dat $RAD_DATA/gases/parsum.dat || \
diff -q parsum_2021.dat parsum_gfortran.dat || ierr=1

if [ $ierr -gt 0 ] ; then
  echo 'HITRAN TIPS are out of date:'
  echo '  * parsum.dat requires updating'
  echo '  * hitran_cnst.f90 requires updating (based on molparam.txt)'
  exit 1
else
  rm -f q*.txt q*.zip parsum_2021.dat molparam.txt 2>/dev/null
  echo 'HITRAN TIPS are up to date'
  echo OK
  exit 0
fi
