#!/bin/bash

# This script creates the 300 band LW spectral file sp_lw_300_jm2
# from scratch using HITRAN database files available in August 2013.
# The following files (available from www.cfa.harvard.edu/hitran)
# are required in HITRAN_DIR (set to your local HITRAN directory):

HITRAN_DIR="$RAD_DATA/gases"

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_O3="$HITRAN_DIR/03_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
HITRAN_O2="$HITRAN_DIR/07_hit12.par"
HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
HITRAN_OCS="$HITRAN_DIR/19_hit12.par"
HITRAN_CFC11="$HITRAN_DIR/CFC-11_IR00.xsc"
HITRAN_CFC12="$HITRAN_DIR/CFC-12_IR00.xsc"
HITRAN_CFC113="$HITRAN_DIR/CFC-113_IR00.xsc"
HITRAN_HCFC22="$HITRAN_DIR/HCFC-22_IR01.xsc"
HITRAN_HFC134a="$HITRAN_DIR/HFC-134a_IR00.xsc"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script takes a very long time to run initially (probably
# several days if not done in parallel). However once the
# line-by-line netCDF files have been created, subsequent runs will
# use these files and the whole script should run in around an hour.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

if [ ! $LW_DATA ] ; then
  LW_DATA=.
fi

pt_file="$RAD_DATA/gases/pt_ses_new"
cfc113_pt_file="$RAD_DATA/gases/pt_cfc113"
ref_pt_file="$RAD_DATA/gases/ref_pt"

# Create skeleton spectral file
specfile="sp_lw_300_skel"
rm -f $specfile
. mk_sp_lw_300_skel > /dev/null

# Hadgem bands ->  300 bands:
#            1 ->    1 -  40
#            2 ->   41 -  55
#            3 ->   56 -  59 +  76 -  80
#            4 ->   60 -  75
#            5 ->   81 -  99 + 113 - 120
#            6 ->  100 - 112
#            7 ->  121 - 133
#            8 ->  134 - 150
#            9 ->  151 - 300

# Gases

echo 'Jobs running in background:'

if [ ! -s co2_l300_l ] || [ ! -s $LW_DATA/co2_lbl_lw.nc ] ; then
  echo 'CO2'
  rm -f co2_l300_l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 1 150 -c 2500.0 -i 0.2 -l 2 1.0e1 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o co2_l300_l -m co2_l300_lm -L $LW_DATA/co2_lbl_lw.nc \
     > co2_l300_log && echo 'CO2 done' &
fi
if [ ! -s co2_nir300_l ] || [ ! -s $LW_DATA/co2_lbl_nir.nc ] ; then
  echo 'CO2 near-IR'
  rm -f co2_nir300_l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 151 300 -c 2500.0 -i 0.2 -l 2 1.0e1 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o co2_nir300_l -m co2_nir300_lm -L $LW_DATA/co2_lbl_nir.nc \
     > co2_nir300_log && echo 'CO2 NIR done' &
fi
if [ ! -s co2_pk300_l ] || [ ! -s $LW_DATA/co2_lbl_pk.nc ] ; then
  echo 'CO2 bands 56-80 (peak) at increased accuracy'
  rm -f co2_pk300_l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 56 80 -c 2500.0 -i 0.05 -l 2 1.0e2 -b 1.0e-4  \
    -s $specfile +p -lk \
    -o co2_pk300_l -m co2_pk300_lm -L $LW_DATA/co2_lbl_pk.nc \
     > co2_pk300_log && echo 'CO2 peak done' &
fi


if [ ! -s o3_l300_l ] || [ ! -s $LW_DATA/o3_lbl_lw.nc ] ; then
  echo 'O3'
  rm -f o3_l300_l*
  Ccorr_k -F $pt_file -D $HITRAN_O3 \
    -R 1 150 -c 2500.0 -i 0.2 -l 3 1.0e-2 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o o3_l300_l -m o3_l300_lm -L $LW_DATA/o3_lbl_lw.nc \
     > o3_l300_log && echo 'O3 done' &
fi
if [ ! -s o3_nir300_l ] || [ ! -s $LW_DATA/o3_lbl_nir.nc ] ; then
  echo 'O3 near-IR'
  rm -f o3_nir300_l*
  Ccorr_k -F $pt_file -D $HITRAN_O3 \
    -R 151 300 -c 2500.0 -i 0.2 -l 3 1.0e-2 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o o3_nir300_l -m o3_nir300_lm -L $LW_DATA/o3_lbl_nir.nc \
     > o3_nir300_log && echo 'O3 NIR done' &
fi
if [ ! -s o3_pk300_l ] || [ ! -s $LW_DATA/o3_lbl_pk.nc ] ; then
  echo 'O3 bands 81-120 (peak) at increased accuracy'
  rm -f o3_pk300_l*
  Ccorr_k -F $pt_file -D $HITRAN_O3 \
    -R 81 120 -c 2500.0 -i 0.05 -l 3 1.0e-1 -b 1.0e-4  \
    -s $specfile +p -lk \
    -o o3_pk300_l -m o3_pk300_lm -L $LW_DATA/o3_lbl_pk.nc \
     > o3_pk300_log && echo 'O3 peak done' &
fi

if [ ! -s ch4_l300_l ] || [ ! -s $LW_DATA/ch4_lbl_lw.nc ] ; then
  echo 'CH4'
  rm -f ch4_l300_l*
  Ccorr_k -F $pt_file -D $HITRAN_CH4 \
    -R 1 150 -c 2500.0 -i 0.2 -l 6 1.0e-2 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o ch4_l300_l -m ch4_l300_lm -L $LW_DATA/ch4_lbl_lw.nc \
     > ch4_l300_log && echo 'CH4 done' &
fi
if [ ! -s ch4_nir300_l ] || [ ! -s $LW_DATA/ch4_lbl_nir.nc ] ; then
  echo 'CH4 near-IR'
  rm -f ch4_nir300_l*
  Ccorr_k -F $pt_file -D $HITRAN_CH4 \
    -R 151 300 -c 2500.0 -i 0.2 -l 6 1.0e-2 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o ch4_nir300_l -m ch4_nir300_lm -L $LW_DATA/ch4_lbl_nir.nc \
     > ch4_nir300_log && echo 'CH4 NIR done' &
fi

echo
echo 'Jobs running in foreground:'

if [ ! -s h2o_l300_l ] || [ ! -s $LW_DATA/h2o_lbl_lwf.nc ] ; then
  echo 'H2O lines and foreign continuum'
  rm -f h2o_l300_l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 1 150 -c 2500.0 -i 0.2 -l 1 1.0e2 -b 1.0e-3  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l300_l -m h2o_l300_lm -L $LW_DATA/h2o_lbl_lwf.nc \
     > h2o_l300_log
fi
if [ ! -s h2o_nir300_l ] || [ ! -s $LW_DATA/h2o_lbl_nirf.nc ] ; then
  echo 'H2O NIR lines and foreign continuum'
  rm -f h2o_nir300_l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 151 300 -c 2500.0 -i 0.2 -l 1 1.0e2 -b 3.0e-3  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_nir300_l -m h2o_nir300_lm -L $LW_DATA/h2o_lbl_nirf.nc \
     > h2o_nir300_log
fi
if [ ! -s h2o_far300_l ] ; then
  echo 'H2O bands 1-40 (far-IR) at increased accuracy'
  rm -f h2o_far300_l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 1 40 -c 2500.0 -i 0.1 -l 1 1.0e2 -b 5.0e-4  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_far300_l -m h2o_far300_lm -L $LW_DATA/h2o_lbl_farf.nc \
     > h2o_far300_log
fi
if [ ! -s h2o_win300_l ] ; then
  echo 'H2O bands 81-112 (window) at increased accuracy'
  rm -f h2o_win300_l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 81 112 -c 2500.0 -i 0.2 -l 1 0.5e1 -t 5.0e-4  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_win300_l -m h2o_win300_lm -L $LW_DATA/h2o_lbl_lwf.nc \
     > h2o_win300_log
fi

if [ ! -s h2o_l300_s ] ; then
  echo 'H2O self-broadened continuum'
  rm -f h2o_l300_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F $pt_file -D $HITRAN_H2O \
    -P 7 -R 1 150 -c 2500.0 -i 0.2 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $specfile +p -q -r $ref_pt_file \
    -o h2o_l300_s -m h2o_l300_sm -L $LW_DATA/h2o_lbl_lwf.nc \
     > h2o_l300_slog
fi
if [ ! -s h2o_nir300_s ] ; then
  echo 'H2O near-IR self-broadened continuum'
  rm -f h2o_nir300_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F $pt_file -D $HITRAN_H2O \
    -P 7 -R 151 300 -c 2500.0 -i 0.2 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $specfile +p -q -r $ref_pt_file \
    -o h2o_nir300_s -m h2o_nir300_sm -L $LW_DATA/h2o_lbl_nirf.nc \
     > h2o_nir300_slog
fi


if [ ! -s n2o_l300_l ] || [ ! -s $LW_DATA/n2o_lbl_lw.nc ] ; then
  echo 'N2O'
  rm -f n2o_l300_l*
  Ccorr_k -F $pt_file -D $HITRAN_N2O \
    -R 1 150 -c 2500.0 -i 0.2 -l 4 5.0e-3 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o n2o_l300_l -m n2o_l300_lm -L $LW_DATA/n2o_lbl_lw.nc \
     > n2o_l300_log
fi
if [ ! -s n2o_nir300_l ] || [ ! -s $LW_DATA/n2o_lbl_nir.nc ] ; then
  echo 'N2O near-IR'
  rm -f n2o_nir300_l*
  Ccorr_k -F $pt_file -D $HITRAN_N2O \
    -R 151 300 -c 2500.0 -i 0.2 -l 4 5.0e-3 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o n2o_nir300_l -m n2o_nir300_lm -L $LW_DATA/n2o_lbl_nir.nc \
     > n2o_nir300_log
fi
if [ ! -s n2o_pk300_l ] ; then
  echo 'N2O bands 56-133 (peak) at increased accuracy'
  rm -f n2o_pk300_l*
  Ccorr_k -F $pt_file -D $HITRAN_N2O \
    -R 56 133 -c 2500.0 -i 0.2 -l 4 5.0e-2 -b 5.0e-4  \
    -s $specfile +p -lk \
    -o n2o_pk300_l -m n2o_pk300_lm -L $LW_DATA/n2o_lbl_lw.nc \
     > n2o_pk300_log
fi


if [ ! -s so2_l300_l ] || [ ! -s $LW_DATA/so2_lbl_lw.nc ] ; then
  echo 'SO2'
  rm -f so2_l300_l*
  Ccorr_k -F $pt_file -D $HITRAN_SO2 \
    -R 1 150 -c 2500.0 -i 0.2 -l 9 3.0e-4 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o so2_l300_l -m so2_l300_lm -L $LW_DATA/so2_lbl_lw.nc \
     > so2_l300_log
fi
if [ ! -s so2_nir300_l ] || [ ! -s $LW_DATA/so2_lbl_nir.nc ] ; then
  echo 'SO2 near-IR'
  rm -f so2_nir300_l*
  Ccorr_k -F $pt_file -D $HITRAN_SO2 \
    -R 151 300 -c 2500.0 -i 0.2 -l 9 3.0e-4 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o so2_nir300_l -m so2_nir300_lm -L $LW_DATA/so2_lbl_nir.nc \
     > so2_nir300_log
fi


if [ ! -s ocs_l300_l ] || [ ! -s $LW_DATA/ocs_lbl_lw.nc ] ; then
  echo 'OCS'
  rm -f ocs_l300_l*
  Ccorr_k -F $pt_file -D $HITRAN_OCS \
    -R 1 150 -c 2500.0 -i 0.2 -l 25 1.0e-3 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o ocs_l300_l -m ocs_l300_lm -L $LW_DATA/ocs_lbl_lw.nc \
     > ocs_l300_log
fi
if [ ! -s ocs_nir300_l ] || [ ! -s $LW_DATA/ocs_lbl_nir.nc ] ; then
  echo 'OCS near-IR'
  rm -f ocs_nir300_l*
  Ccorr_k -F $pt_file -D $HITRAN_OCS \
    -R 151 300 -c 2500.0 -i 0.2 -l 25 1.0e-3 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o ocs_nir300_l -m ocs_nir300_lm -L $LW_DATA/ocs_lbl_nir.nc \
     > ocs_nir300_log
fi


# Halocarbons

if [ ! -s cfc11_l300_l ] ; then
  echo 'CFC 11'
  rm -f cfc11_l300_l*
  Ccorr_k -F $pt_file -X $HITRAN_CFC11 \
    -R 81 120 -i 1.0 -l 14 0.1e-4 -t 1.0e-4 \
    -s $specfile +p -lk \
    -o cfc11_l300_l -m cfc11_l300_lm -L $LW_DATA/cfc11_lbl_lw.nc \
     > cfc11_l300_log
fi

if [ ! -s cfc12_l300_l ] ; then
  echo 'CFC 12'
  rm -f cfc12_l300_l*
  Ccorr_k -F $pt_file -X $HITRAN_CFC12 \
    -R 81 120 -i 1.0 -l 15 0.2e-4 -t 1.0e-4 \
    -s $specfile +p -lk \
    -o cfc12_l300_l -m cfc12_l300_lm -L $LW_DATA/cfc12_lbl_lw.nc \
     > cfc12_l300_log
fi

if [ ! -s cfc113_l300_l ] ; then
  echo 'CFC 113'
  rm -f cfc113_l300_l*
  Ccorr_k -F $cfc113_pt_file -X $HITRAN_CFC113 \
    -R 56 133 -i 1.0 -l 16 0.4e-5 -t 1.0e-4 \
    -s $specfile +p -q -r $ref_pt_file \
    -o cfc113_l300_l -m cfc113_l300_lm -L $LW_DATA/cfc113_lbl_lw.nc \
     > cfc113_l300_log
fi

if [ ! -s hcfc22_l300_l ] ; then
  echo 'HCFC 22'
  rm -f hcfc22_l300_l*
  Ccorr_k -F $pt_file -X $HITRAN_HCFC22 \
    -R 56 150 -i 1.0 -l 17 0.6e-5 -t 1.0e-4 \
    -s $specfile +p -lk \
    -o hcfc22_l300_l -m hcfc22_l300_lm -L $LW_DATA/hcfc22_lbl_lw.nc \
     > hcfc22_l300_log
fi

if [ ! -s hfc134a_l300_l ] ; then
  echo 'HFC 134a'
  rm -f hfc134a_l300_l*
  Ccorr_k -F $pt_file -X $HITRAN_HFC134a \
    -R 81 150 -i 1.0 -l 19 0.3e-5 -t 1.0e-4 \
    -s $specfile +p -lk \
    -o hfc134a_l300_l -m hfc134a_l300_lm -L $LW_DATA/hfc134a_lbl_lw.nc \
     > hfc134a_l300_log
fi

wait
# Now run jobs that require files created above.

if [ ! -s co2_win300_l ] ; then
  echo 'CO2 bands 81-120 (window) at increased accuracy'
  rm co2_win300_l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 81 120 -c 2500.0 -i 0.2 -l 2 1.0e2 -b 1.0e-4  \
    -s $specfile +p -lk \
    -o co2_win300_l -m co2_win300_lm -L $LW_DATA/co2_lbl_lw.nc \
     > co2_win300_log
fi

if [ ! -s o3_mp300_l ] ; then
  echo 'O3 bands 56-80 (minor peak) at increased accuracy'
  rm o3_mp300_l*
  Ccorr_k -F $pt_file -D $HITRAN_O3 \
    -R 56 80 -c 2500.0 -i 0.2 -l 3 1.0e-1 -b 1.0e-4  \
    -s $specfile +p -lk \
    -o o3_mp300_l -m o3_mp300_lm -L $LW_DATA/o3_lbl_lw.nc \
     > o3_mp300_log
fi


# Cloud

if [ ! -s fit_lw_drop5_300 ] ; then
  echo 'Type 5 droplets'
  rm -f mon_lw_drop5_300
  Cscatter_average -s $specfile -P 1 -t -p 250 \
    -f 5 fit_lw_drop5_300 mon_lw_drop5_300 1.e3 \
    $RAD_DATA/cloud/scatter_drop_type5
fi
if [ ! -s fit_lw_ice8_300 ] ; then
  echo 'Type 8 ice'
  rm -f mon_lw_ice8_300
  Cscatter_average -s $specfile -P 1 -w -p 250 \
    -f 12 fit_lw_ice8_300 mon_lw_ice8_300 920 \
    $RAD_DATA/cloud/scatter_ice_lw_type8
fi


# Aerosols

if [ ! -s soluble_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a soluble_300.avg $RAD_DATA/aerosol/soluble.mon
fi
if [ ! -s dustlike_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dustlike_300.avg $RAD_DATA/aerosol/dustlike.mon
fi
if [ ! -s oceanic_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a oceanic_300.avg $RAD_DATA/aerosol/oceanic.mon
fi
if [ ! -s soot_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a soot_300.avg $RAD_DATA/aerosol/soot.mon
fi
if [ ! -s sulphuric_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a sulphuric_300.avg $RAD_DATA/aerosol/sulphuric.mon
fi
if [ ! -s accumsulp_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a accumsulp_300.avg $RAD_DATA/aerosol/accumsulp.mon
fi
if [ ! -s aitkensulp_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a aitkensulp_300.avg $RAD_DATA/aerosol/aitkensulp.mon
fi
if [ ! -s freshsoot_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a freshsoot_300.avg $RAD_DATA/aerosol/freshsoot.mon
fi
if [ ! -s agedsoot_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a agedsoot_300.avg $RAD_DATA/aerosol/agedsoot.mon
fi
if [ ! -s seasaltfilm_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a seasaltfilm_300.avg $RAD_DATA/aerosol/seasaltfilm.mon
fi
if [ ! -s seasaltjet_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a seasaltjet_300.avg $RAD_DATA/aerosol/seasaltjet.mon
fi
if [ ! -s dust_div1_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div1_300.avg $RAD_DATA/aerosol/dust_div1.mon
fi
if [ ! -s dust_div2_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div2_300.avg $RAD_DATA/aerosol/dust_div2.mon
fi
if [ ! -s dust_div3_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div3_300.avg $RAD_DATA/aerosol/dust_div3.mon
fi
if [ ! -s dust_div4_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div4_300.avg $RAD_DATA/aerosol/dust_div4.mon
fi
if [ ! -s dust_div5_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div5_300.avg $RAD_DATA/aerosol/dust_div5.mon
fi
if [ ! -s dust_div6_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div6_300.avg $RAD_DATA/aerosol/dust_div6.mon
fi
if [ ! -s freshbiomass_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a freshbiomass_300.avg $RAD_DATA/aerosol/freshbiomass.mon
fi
if [ ! -s agedbiomass_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a agedbiomass_300.avg $RAD_DATA/aerosol/agedbiomass.mon
fi
if [ ! -s biogenic_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a biogenic_300.avg $RAD_DATA/aerosol/biogenic.mon
fi
if [ ! -s freshocff_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a freshocff_300.avg $RAD_DATA/aerosol/freshocff.mon
fi
if [ ! -s agedocff_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a agedocff_300.avg $RAD_DATA/aerosol/agedocff.mon
fi
if [ ! -s nitrate_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a nitrate_300.avg $RAD_DATA/aerosol/nitrate.mon
fi
if [ ! -s twobindust_1_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 290 \
  -a twobindust_1_300.avg $RAD_DATA/aerosol/twobindust_1.mon
fi
if [ ! -s twobindust_2_300.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 290 \
  -a twobindust_2_300.avg $RAD_DATA/aerosol/twobindust_2.mon
fi

mv sp_lw_300_jm2 sp_lw_300_jm2_old
mv sp_lw_300_jm2_k sp_lw_300_jm2_old_k
# Construct spectral file
prep_spec << EOF
sp_lw_300_skel
n
sp_lw_300_jm2
6
n
p
160 330
4
5
h2o_l300_l
5
y
h2o_nir300_l
5
y
h2o_far300_l
5
y
h2o_win300_l
9
h2o_l300_s
9
y
h2o_nir300_s
5
y
co2_l300_l
5
y
co2_nir300_l
5
y
co2_pk300_l
5
y
co2_win300_l
5
y
o3_l300_l
5
y
o3_nir300_l
5
y
o3_pk300_l
5
y
o3_mp300_l
5
y
n2o_l300_l
5
y
n2o_nir300_l
5
y
n2o_pk300_l
5
y
ch4_l300_l
5
y
ch4_nir300_l
5
y
so2_l300_l
5
y
so2_nir300_l
5
y
ocs_l300_l
5
y
ocs_nir300_l
5
y
cfc11_l300_l
5
y
cfc12_l300_l
5
y
cfc113_l300_l
5
y
hcfc22_l300_l
5
y
hfc134a_l300_l
10
5
fit_lw_drop5_300
1.50000E-06 5.00000E-05
12
8
fit_lw_ice8_300
11
soluble_300.avg
11
dustlike_300.avg
11
oceanic_300.avg
11
soot_300.avg
11
sulphuric_300.avg
11
accumsulp_300.avg
11
aitkensulp_300.avg
11
freshsoot_300.avg
11
agedsoot_300.avg
11
seasaltfilm_300.avg
11
seasaltjet_300.avg
11
dust_div1_300.avg
11
dust_div2_300.avg
11
dust_div3_300.avg
11
dust_div4_300.avg
11
dust_div5_300.avg
11
dust_div6_300.avg
11
freshbiomass_300.avg
11
agedbiomass_300.avg
11
biogenic_300.avg
11
freshocff_300.avg
11
agedocff_300.avg
11
nitrate_300.avg
11
twobindust_1_300.avg
11
twobindust_2_300.avg
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 <<EOF
sp_lw_300_jm2
o
1
2.5e1
1.0e1
0.1e-1
0.5e-2
0.1e-1
3.0e-2
0.1e-4
0.2e-4
0.4e-5
0.6e-5
0.3e-5
1.0e-1
0.999990
6
2.5e1
1.0e1
0.1e-1
0.5e-2
0.1e-1
3.0e-6
0.1e-4
0.2e-4
0.4e-5
0.6e-5
0.3e-5
1.0e-5
-1
EOF

exit 0
