#!/bin/bash

# This script creates the 9 band LW spectral file sp_lw_9_jm3
# using HITRAN database files available in August 2013.
# The following files (available from www.cfa.harvard.edu/hitran)
# are required in HITRAN_DIR (set to your local HITRAN directory):

HITRAN_DIR="$RAD_DATA/gases"

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_O3="$HITRAN_DIR/03_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
HITRAN_O2="$HITRAN_DIR/07_hit12.par"
HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
HITRAN_OCS="$HITRAN_DIR/19_hit12.par"
HITRAN_CFC11="$HITRAN_DIR/CFC-11_IR00.xsc"
HITRAN_CFC12="$HITRAN_DIR/CFC-12_IR00.xsc"
HITRAN_CFC113="$HITRAN_DIR/CFC-113_IR00.xsc"
HITRAN_HCFC22="$HITRAN_DIR/HCFC-22_IR01.xsc"
HITRAN_HFC134a="$HITRAN_DIR/HFC-134a_IR00.xsc"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script should be run after the LbL files have been created
# by running the script for the 300 band file.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

if [ ! $LW_DATA ] ; then
  LW_DATA=.
fi

pt_file="$RAD_DATA/gases/pt_ses_new"
cfc113_pt_file="$RAD_DATA/gases/pt_cfc113"
ref_pt_file="$RAD_DATA/gases/ref_pt"

# Create skeleton spectral file
specfile="sp_lw_9_skel"
rm -f $specfile
. mk_sp_lw_9_skel > /dev/null


# Hadgem bands ->  300 bands:
#            1 ->    1 -  40
#            2 ->   41 -  55
#            3 ->   56 -  59 +  76 -  80
#            4 ->   60 -  75
#            5 ->   81 -  99 + 113 - 120
#            6 ->  100 - 112
#            7 ->  121 - 133
#            8 ->  134 - 150
#            9 ->  151 - 300

# Gases

echo 'H2O lines and foreign continuum'
if [ ! -s h2o_l9_1l ] ; then
  rm h2o_l9_1l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 1 1 -c 2500.0 -i 0.1 -l 1 1.0e2 -b 2.2e-3  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l9_1l -m h2o_l9_1lm -L $LW_DATA/h2o_lbl_farf.nc
fi
if [ ! -s h2o_l9_2l ] ; then
  rm h2o_l9_2l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 2 2 -c 2500.0 -i 0.2 -l 1 2.5e1 -n 14  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l9_2l -m h2o_l9_2lm -L $LW_DATA/h2o_lbl_lwf.nc
fi
if [ ! -s h2o_l9_3l ] ; then
  rm h2o_l9_3l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 0.2 -l 1 2.5e1 -n 5 \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l9_3l -m h2o_l9_3lm -L $LW_DATA/h2o_lbl_lwf.nc
fi
if [ ! -s h2o_l9_4l ] ; then
  rm h2o_l9_4l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 4 4 -c 2500.0 -i 0.2 -l 1 0.5e1 -n 4  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l9_4l -m h2o_l9_4lm -L $LW_DATA/h2o_lbl_lwf.nc
fi
if [ ! -s h2o_l9_5l ] ; then
  rm h2o_l9_5l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 5 5 -c 2500.0 -i 0.2 -l 1 0.5e1 -n 6  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l9_5l -m h2o_l9_5lm -L $LW_DATA/h2o_lbl_lwf.nc
fi
if [ ! -s h2o_l9_6l ] ; then
  rm h2o_l9_6l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 6 6 -c 2500.0 -i 0.2 -l 1 0.5e1 -n 3  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l9_6l -m h2o_l9_6lm -L $LW_DATA/h2o_lbl_lwf.nc
fi
if [ ! -s h2o_l9_7l ] ; then
  rm h2o_l9_7l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 7 7 -c 2500.0 -i 0.2 -l 1 0.5e1 -n 5  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l9_7l -m h2o_l9_7lm -L $LW_DATA/h2o_lbl_lwf.nc
fi
if [ ! -s h2o_l9_8l ] ; then
  rm h2o_l9_8l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 8 8 -c 2500.0 -i 0.2 -l 1 0.5e1 -n 5  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l9_8l -m h2o_l9_8lm -L $LW_DATA/h2o_lbl_lwf.nc
fi
if [ ! -s h2o_l9_9l ] ; then
  rm h2o_l9_9l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 9 9 -c 2500.0 -i 0.2 -l 1 1.0e2 -n 5  \
    -s $specfile +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_l9_9l -m h2o_l9_9lm -L $LW_DATA/h2o_lbl_nirf.nc
fi

echo 'Self-broadened continuum'
if [ ! -s h2o_l9_s ] ; then
  rm h2o_l9_s*
  Ccorr_k -C 17 2.5e-1 2.5e2 -F $pt_file -D $HITRAN_H2O \
    -P 7 -R 2 8 -c 2500.0 -i 0.2 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $specfile +p -q -r $ref_pt_file \
    -o h2o_l9_s -m h2o_l9_sm -L $LW_DATA/h2o_lbl_lwf.nc
fi


echo 'CO2'
if [ ! -s co2_l9_3l ] ; then
  rm co2_l9_3l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 3 3 -c 2500.0 -i 0.2 -l 2 0.5e1 -b 2.5e-3  \
    -s $specfile +p -lk \
    -o co2_l9_3l -m co2_l9_3lm -L $LW_DATA/co2_lbl_lw.nc
fi
if [ ! -s co2_l9_4l ] ; then
  rm co2_l9_4l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 4 4 -c 2500.0 -i 0.05 -l 2 1.0e2 -b 1.5e-3  \
    -s $specfile +p -lk \
    -o co2_l9_4l -m co2_l9_4lm -L $LW_DATA/co2_lbl_pk.nc
fi
if [ ! -s co2_l9_5l ] ; then
  rm co2_l9_5l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 5 5 -c 2500.0 -i 0.2 -l 2 0.5e1 -b 1.5e-3  \
    -s $specfile +p -lk \
    -o co2_l9_5l -m co2_l9_5lm -L $LW_DATA/co2_lbl_lw.nc
fi
if [ ! -s co2_l9_6l ] ; then
  rm co2_l9_6l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 6 6 -c 2500.0 -i 0.2 -l 2 0.5e1 -b 2.5e-3  \
    -s $specfile +p -lk \
    -o co2_l9_6l -m co2_l9_6lm -L $LW_DATA/co2_lbl_lw.nc
fi

echo 'O3'
if [ ! -s o3_l9_3l ] ; then
  rm o3_l9_3l*
  Ccorr_k -F $pt_file -D $HITRAN_O3 \
    -R 3 3 -c 2500.0 -i 0.2 -l 3 2.0e-4 -n 1  \
    -s $specfile +p -lk \
    -o o3_l9_3l -m o3_l9_3lm -L $LW_DATA/o3_lbl_lw.nc
fi
if [ ! -s o3_l9_4l ] ; then
  rm o3_l9_4l*
  Ccorr_k -F $pt_file -D $HITRAN_O3 \
    -R 4 4 -c 2500.0 -i 0.2 -l 3 2.0e-4 -n 4  \
    -s $specfile +p -lk \
    -o o3_l9_4l -m o3_l9_4lm -L $LW_DATA/o3_lbl_lw.nc
fi
if [ ! -s o3_l9_6l ] ; then
  rm o3_l9_6l*
  Ccorr_k -F $pt_file -D $HITRAN_O3 \
    -R 6 6 -c 2500.0 -i 0.2 -l 3 2.0e-2 -n 10  \
    -s $specfile +p -lk \
    -o o3_l9_6l -m o3_l9_6lm -L $LW_DATA/o3_lbl_lw.nc
fi

echo 'N2O'
if [ ! -s n2o_l9_3l ] ; then
  rm n2o_l9_3l*
  Ccorr_k -F $pt_file -D $HITRAN_N2O \
    -R 3 3 -c 2500.0 -i 0.2 -l 4 5.0e-3 -n 2  \
    -s $specfile +p -lk \
    -o n2o_l9_3l -m n2o_l9_3lm -L $LW_DATA/n2o_lbl_lw.nc
fi
if [ ! -s n2o_l9_5l ] ; then
  rm n2o_l9_5l*
  Ccorr_k -F $pt_file -D $HITRAN_N2O \
    -R 5 5 -c 2500.0 -i 0.2 -l 4 1.0e-3 -n 2 \
    -s $specfile +p -lk \
    -o n2o_l9_5l -m n2o_l9_5lm -L $LW_DATA/n2o_lbl_lw.nc
fi
if [ ! -s n2o_l9_7l ] ; then
  rm n2o_l9_7l*
  Ccorr_k -F $pt_file -D $HITRAN_N2O \
    -R 7 7 -c 2500.0 -i 0.2 -l 4 0.5e-3 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o n2o_l9_7l -m n2o_l9_7lm -L $LW_DATA/n2o_lbl_lw.nc
fi
if [ ! -s n2o_l9_8l ] ; then
  rm n2o_l9_8l*
  Ccorr_k -F $pt_file -D $HITRAN_N2O \
    -R 8 8 -c 2500.0 -i 0.2 -l 4 5.0e-3 -n 1  \
    -s $specfile +p -lk \
    -o n2o_l9_8l -m n2o_l9_8lm -L $LW_DATA/n2o_lbl_lw.nc
fi

echo 'CH4'
if [ ! -s ch4_l9_7l ] ; then
  rm ch4_l9_7l*
  Ccorr_k -F $pt_file -D $HITRAN_CH4 \
    -R 7 7 -c 2500.0 -i 0.2 -l 6 2.5e-3 -b 2.0e-3 \
    -s $specfile +p -lk \
    -o ch4_l9_7l -m ch4_l9_7lm -L $LW_DATA/ch4_lbl_lw.nc
fi
if [ ! -s ch4_l9_8l ] ; then
  rm ch4_l9_8l*
  Ccorr_k -F $pt_file -D $HITRAN_CH4 \
    -R 8 8 -c 2500.0 -i 0.2 -l 6 5.0e-3 -n 3  \
    -s $specfile +p -lk \
    -o ch4_l9_8l -m ch4_l9_8lm -L $LW_DATA/ch4_lbl_lw.nc
fi

echo 'SO2'
if [ ! -s so2_l9_l ] ; then
  rm -f so2_l9_l*
  Ccorr_k -F $pt_file -D $HITRAN_SO2 \
    -R 1 8 -c 2500.0 -i 0.2 -l 9 3.0e-4 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o so2_l9_l -m so2_l9_lm -L $LW_DATA/so2_lbl_lw.nc
fi
if [ ! -s so2_nir9_l ] ; then
  rm -f so2_nir9_l*
  Ccorr_k -F $pt_file -D $HITRAN_SO2 \
    -R 9 9 -c 2500.0 -i 0.2 -l 9 3.0e-4 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o so2_nir9_l -m so2_nir9_lm -L $LW_DATA/so2_lbl_nir.nc
fi

echo 'OCS'
if [ ! -s ocs_l9_l ] ; then
  rm -f ocs_l9_l*
  Ccorr_k -F $pt_file -D $HITRAN_OCS \
    -R 1 8 -c 2500.0 -i 0.2 -l 25 1.0e-3 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o ocs_l9_l -m ocs_l9_lm -L $LW_DATA/ocs_lbl_lw.nc
fi
if [ ! -s ocs_nir9_l ] ; then
  rm -f ocs_nir9_l*
  Ccorr_k -F $pt_file -D $HITRAN_OCS \
    -R 9 9 -c 2500.0 -i 0.2 -l 25 1.0e-3 -b 1.0e-3  \
    -s $specfile +p -lk \
    -o ocs_nir9_l -m ocs_nir9_lm -L $LW_DATA/ocs_lbl_nir.nc
fi


# Halocarbons

echo 'CFC 11'
if [ ! -s cfc11_l9_l ] ; then
  rm cfc11_l9_l*
  Ccorr_k -F $pt_file -X $HITRAN_CFC11 \
    -R 5 6 -i 1.0 -l 14 0.1e-4 -t 1.0e-3 \
    -s $specfile +p -lk \
    -o cfc11_l9_l -m cfc11_l9_lm -L $LW_DATA/cfc11_lbl_lw.nc
fi

echo 'CFC 12'
if [ ! -s cfc12_l9_l ] ; then
  rm cfc12_l9_l*
  Ccorr_k -F $pt_file -X $HITRAN_CFC12 \
    -R 5 6 -i 1.0 -l 15 0.2e-4 -t 1.0e-3 \
    -s $specfile +p -lk \
    -o cfc12_l9_l -m cfc12_l9_lm -L $LW_DATA/cfc12_lbl_lw.nc
fi

echo 'CFC 113'
if [ ! -s cfc113_l9_l ] ; then
  rm cfc113_l9_l*
  Ccorr_k -F $cfc113_pt_file -X $HITRAN_CFC113 \
    -R 3 7 -i 1.0 -l 16 0.4e-5 -t 1.0e-3 \
    -s $specfile +p -q -r $ref_pt_file \
    -o cfc113_l9_l -m cfc113_l9_lm -L $LW_DATA/cfc113_lbl_lw.nc
fi

echo 'HCFC 22'
if [ ! -s hcfc22_l9_l ] ; then
  rm hcfc22_l9_l*
  Ccorr_k -F $pt_file -X $HITRAN_HCFC22 \
    -R 3 8 -i 1.0 -l 17 0.6e-5 -t 1.0e-3 \
    -s $specfile +p -lk \
    -o hcfc22_l9_l -m hcfc22_l9_lm -L $LW_DATA/hcfc22_lbl_lw.nc
fi

echo 'HFC 134a'
if [ ! -s hfc134a_l9_l ] ; then
  rm hfc134a_l9_l*
  Ccorr_k -F $pt_file -X $HITRAN_HFC134a \
    -R 5 8 -i 1.0 -l 19 0.3e-5 -t 1.0e-3 \
    -s $specfile +p -lk \
    -o hfc134a_l9_l -m hfc134a_l9_lm -L $LW_DATA/hfc134a_lbl_lw.nc
fi


# Cloud

if [ ! -s fit_lw_drop5_9 ] ; then
  rm -f mon_lw_drop5_9
  Cscatter_average -s $specfile -P 1 -t -p 250 \
    -f 5 fit_lw_drop5_9 mon_lw_drop5_9 1.e3 \
    $RAD_DATA/cloud/scatter_drop_lw_type5
fi
if [ ! -s fit_lw_ice8_9 ] ; then
  rm -f mon_lw_ice8_9
  Cscatter_average -s $specfile -P 1 -w -p 250 \
    -f 12 fit_lw_ice8_9 mon_lw_ice8_9 920 \
    $RAD_DATA/cloud/scatter_ice_lw_type8
fi


# Aerosols

if [ ! -s soluble_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a soluble_9.avg $RAD_DATA/aerosol/soluble.mon
fi
if [ ! -s dustlike_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dustlike_9.avg $RAD_DATA/aerosol/dustlike.mon
fi
if [ ! -s oceanic_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a oceanic_9.avg $RAD_DATA/aerosol/oceanic.mon
fi
if [ ! -s soot_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a soot_9.avg $RAD_DATA/aerosol/soot.mon
fi
if [ ! -s sulphuric_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a sulphuric_9.avg $RAD_DATA/aerosol/sulphuric.mon
fi
if [ ! -s accumsulp_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a accumsulp_9.avg $RAD_DATA/aerosol/accumsulp.mon
fi
if [ ! -s aitkensulp_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a aitkensulp_9.avg $RAD_DATA/aerosol/aitkensulp.mon
fi
if [ ! -s freshsoot_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a freshsoot_9.avg $RAD_DATA/aerosol/freshsoot.mon
fi
if [ ! -s agedsoot_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a agedsoot_9.avg $RAD_DATA/aerosol/agedsoot.mon
fi
if [ ! -s seasaltfilm_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a seasaltfilm_9.avg $RAD_DATA/aerosol/seasaltfilm.mon
fi
if [ ! -s seasaltjet_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a seasaltjet_9.avg $RAD_DATA/aerosol/seasaltjet.mon
fi
if [ ! -s dust_div1_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div1_9.avg $RAD_DATA/aerosol/dust_div1.mon
fi
if [ ! -s dust_div2_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div2_9.avg $RAD_DATA/aerosol/dust_div2.mon
fi
if [ ! -s dust_div3_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div3_9.avg $RAD_DATA/aerosol/dust_div3.mon
fi
if [ ! -s dust_div4_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div4_9.avg $RAD_DATA/aerosol/dust_div4.mon
fi
if [ ! -s dust_div5_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div5_9.avg $RAD_DATA/aerosol/dust_div5.mon
fi
if [ ! -s dust_div6_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a dust_div6_9.avg $RAD_DATA/aerosol/dust_div6.mon
fi
if [ ! -s freshbiomass_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a freshbiomass_9.avg $RAD_DATA/aerosol/freshbiomass.mon
fi
if [ ! -s agedbiomass_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a agedbiomass_9.avg $RAD_DATA/aerosol/agedbiomass.mon
fi
if [ ! -s biogenic_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a biogenic_9.avg $RAD_DATA/aerosol/biogenic.mon
fi
if [ ! -s freshocff_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a freshocff_9.avg $RAD_DATA/aerosol/freshocff.mon
fi
if [ ! -s agedocff_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a agedocff_9.avg $RAD_DATA/aerosol/agedocff.mon
fi
if [ ! -s nitrate_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 250 \
  -a nitrate_9.avg $RAD_DATA/aerosol/nitrate.mon
fi
if [ ! -s twobindust_1_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 290 \
  -a twobindust_1_9.avg $RAD_DATA/aerosol/twobindust_1.mon
fi
if [ ! -s twobindust_2_9.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -p 290 \
  -a twobindust_2_9.avg $RAD_DATA/aerosol/twobindust_2.mon
fi


# Construct spectral file

mv sp_lw_9_jm3 sp_lw_9_jm3_old
mv sp_lw_9_jm3_k sp_lw_9_jm3_old_k
prep_spec << EOF
sp_lw_9_skel
n
sp_lw_9_jm3
6
n
p
160 330
4
5
h2o_l9_1l
5
y
h2o_l9_2l
5
y
h2o_l9_3l
5
y
h2o_l9_4l
5
y
h2o_l9_5l
5
y
h2o_l9_6l
5
y
h2o_l9_7l
5
y
h2o_l9_8l
5
y
h2o_l9_9l
9
h2o_l9_s
5
y
co2_l9_3l
5
y
co2_l9_4l
5
y
co2_l9_5l
5
y
co2_l9_6l
5
y
o3_l9_3l
5
y
o3_l9_4l
5
y
o3_l9_6l
5
y
n2o_l9_3l
5
y
n2o_l9_5l
5
y
n2o_l9_7l
5
y
n2o_l9_8l
5
y
ch4_l9_7l
5
y
ch4_l9_8l
5
y
so2_l9_l
5
y
so2_nir9_l
5
y
ocs_l9_l
5
y
ocs_nir9_l
5
y
cfc11_l9_l
5
y
cfc12_l9_l
5
y
cfc113_l9_l
5
y
hcfc22_l9_l
5
y
hfc134a_l9_l
10
5
fit_lw_drop5_9
1.50000E-06 5.00000E-05
12
8
fit_lw_ice8_9
11
soluble_9.avg
11
dustlike_9.avg
11
oceanic_9.avg
11
soot_9.avg
11
sulphuric_9.avg
11
accumsulp_9.avg
11
aitkensulp_9.avg
11
freshsoot_9.avg
11
agedsoot_9.avg
11
seasaltfilm_9.avg
11
seasaltjet_9.avg
11
dust_div1_9.avg
11
dust_div2_9.avg
11
dust_div3_9.avg
11
dust_div4_9.avg
11
dust_div5_9.avg
11
dust_div6_9.avg
11
freshbiomass_9.avg
11
agedbiomass_9.avg
11
biogenic_9.avg
11
freshocff_9.avg
11
agedocff_9.avg
11
nitrate_9.avg
11
twobindust_1_9.avg
11
twobindust_2_9.avg
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 <<EOF
sp_lw_9_jm3
o
1
2.5e1
1.0e1
0.1e-1
0.5e-2
0.1e-1
3.0e-2
0.1e-4
0.2e-4
0.4e-5
0.6e-5
0.3e-5
1.0e-1
0.99990
6
2.5e1
1.0e1
0.1e-1
0.5e-2
0.1e-1
3.0e-6
0.1e-4
0.2e-4
0.4e-5
0.6e-5
0.3e-5
1.0e-5
-1
EOF

exit 0
