#!/bin/bash

# This script creates the 260 band SW spectral file sp_sw_260_jm2
# from scratch using HITRAN database files available in August 2013.
# The following files (available from www.cfa.harvard.edu/hitran)
# are required in HITRAN_DIR (set to your local HITRAN directory):

HITRAN_DIR="$RAD_DATA/gases"

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_O3="$HITRAN_DIR/03_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_UV_N2O="$HITRAN_DIR/N2O-UV00.xsc"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
HITRAN_O2="$HITRAN_DIR/07_hit12.par"
HITRAN_UV_O2="$HITRAN_DIR/07_UV06.par"
HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
HITRAN_UV_SO2="$HITRAN_DIR/SO2_UV08.xsc"
HITRAN_OCS="$HITRAN_DIR/19_hit12.par"

HITRAN_UV_O3="$RAD_DATA/gases/ser_bdm_o3.xsc"
JPL_UV_O2="$RAD_DATA/gases/jpl_o2.xsc"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script takes a very long time to run initially (probably
# several days if not done in parallel). However once the
# line-by-line netCDF files have been created, subsequent runs will
# use these files and the whole script should run in around an hour.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

echo 'Running mk_sp_sw_260_jm2'
echo -n 'Started: '; date

if [ ! $SW_DATA ] ; then
  SW_DATA=.
fi

procs=24

solspec='lean_12'
pt_file="$RAD_DATA/gases/pt_ses_new"
o3_pt_file="$RAD_DATA/gases/pt_o3_ser"
o2_pt_file="$RAD_DATA/gases/pt_o2_jpl"
n2o_pt_file="$RAD_DATA/gases/pt_n2o_uv"
so2_pt_file="$RAD_DATA/gases/pt_so2_uv"
ref_pt_file="$RAD_DATA/gases/ref_pt"

# Create skeleton spectral file
specfile="sp_sw_260_skel"
rm -f $specfile
. mk_sp_sw_260_skel > /dev/null

# Hadgem bands ->  220        ->  260 bands:
#            1 ->    1 -  38  ->  1/6 -  29
#            2 ->   38 -  91  ->   30 -  66
#            3 ->   91 - 118  ->   67 - 103
#            4 ->  118 - 148  ->  104 - 154
#            5 ->  148 - 188  ->  155 - 214
#            6 ->  188 - 220  ->  215 - 260

# Gases

if [ ! -s h2o_s260_l ] || [ ! -s $SW_DATA/h2o_lbl_swf.nc ] ; then
  echo 'H2O lines (near-IR)'
  rm -f h2o_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 66 260 -c 2500.0 -i 1.0 -l 1 1.0e2 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_s260_l -m h2o_s260_lm -L $SW_DATA/h2o_lbl_swf.nc \
    -np $procs \
     > h2o_s260_log
fi
if [ ! -s h2o_v260_l ] || [ ! -s $SW_DATA/h2o_lbl_vis.nc ] ; then
  echo 'H2O lines (visible)'
  rm -f h2o_v260_l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 30 65 -c 2500.0 -i 1.0 -l 1 1.0e2 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o h2o_v260_l -m h2o_v260_lm -L $SW_DATA/h2o_lbl_vis.nc \
    -np $procs \
     > h2o_v260_log
fi

if [ ! -s h2o_s260_s ] ; then
  echo 'H2O self-broadened continuum'
  rm -f h2o_s260_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F $pt_file -D $HITRAN_H2O \
    -P 7 -R 66 260 -c 2500.0 -i 1.0 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $specfile +S $solspec -q -r $ref_pt_file \
    -o h2o_s260_s -m h2o_s260_sm -L $SW_DATA/h2o_lbl_swf.nc \
    -np $procs \
     > h2o_s260_slog
fi

if [ ! -s co2_s260_l ] || [ ! -s $SW_DATA/co2_lbl_sw.nc ] ; then
  echo 'CO2'
  rm -f co2_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 104 260 -c 2500.0 -i 1.0 -l 2 1.0e1 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o co2_s260_l -m co2_s260_lm -L $SW_DATA/co2_lbl_sw.nc \
    -np $procs \
     > co2_s260_log
fi

if [ ! -s o3_u260_l ] || [ ! -s $SW_DATA/o3_lbl_uv.nc ] ; then
  echo 'O3'
  rm -f o3_u260_l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R 5 154 -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-4  \
    -s $specfile +S $solspec -q -r $ref_pt_file \
    -o o3_u260_l -m o3_u260_lm -L $SW_DATA/o3_lbl_uv.nc \
    -np $procs \
     > o3_u260_log
fi
if [ ! -s o3_s260_l ] || [ ! -s $SW_DATA/o3_lbl_sw.nc ] ; then
  echo 'O3 (near-IR)'
  rm -f o3_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_O3 \
    -R 155 260 -c 2500.0 -i 1.0 -l 3 1.0e-2 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o o3_s260_l -m o3_s260_lm -L $SW_DATA/o3_lbl_sw.nc \
    -np $procs \
     > o3_s260_log
fi

if [ ! -s n2o_s260_l ] || [ ! -s $SW_DATA/n2o_lbl_sw.nc ] ; then
  echo 'N2O'
  rm -f n2o_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_N2O \
    -R 155 260 -c 2500.0 -i 1.0 -l 4 5.0e-3 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o n2o_s260_l -m n2o_s260_lm -L $SW_DATA/n2o_lbl_sw.nc \
    -np $procs \
     > n2o_s260_log
fi
if [ ! -s n2o_u260_l ] || [ ! -s $SW_DATA/n2o_lbl_uv.nc ] ; then
  echo 'N2O (UV)'
  rm -f n2o_u260_l*
  Ccorr_k -F $n2o_pt_file -X $HITRAN_UV_N2O \
    -R 1 10 -c 2500.0 -i 1.0 -l 4 5.0e-3 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o n2o_u260_l -m n2o_u260_lm -L $SW_DATA/n2o_lbl_uv.nc \
    -np $procs \
     > n2o_u260_log
fi

if [ ! -s ch4_s260_l ] || [ ! -s $SW_DATA/ch4_lbl_sw.nc ] ; then
  echo 'CH4'
  rm -f ch4_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_CH4 \
    -R 104 260 -c 2500.0 -i 1.0 -l 6 1.0e-2 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o ch4_s260_l -m ch4_s260_lm -L $SW_DATA/ch4_lbl_sw.nc \
    -np $procs \
     > ch4_s260_log
fi

if [ ! -s o2_j260_l ] || [ ! -s $SW_DATA/o2_lbl_jpl.nc ] ; then
  echo 'O2 (UV continuum: JPL)'
  rm -f o2_j260_l*
  Ccorr_k -F $o2_pt_file -X $JPL_UV_O2 \
    -R 7 14 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o o2_j260_l -m o2_j260_lm -L $SW_DATA/o2_lbl_jpl.nc \
    -np $procs \
     > o2_j260_log
fi
if [ ! -s o2_u260_l ] || [ ! -s $SW_DATA/o2_lbl_uv.nc ] ; then
  echo 'O2 (UV lines: HITRAN)'
  rm -f o2_u260_l*
  Ccorr_k -F $pt_file -D $HITRAN_UV_O2 \
    -R 1 29 -c 2500.0 -i 1.0 -l 7 2.3e3 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o o2_u260_l -m o2_u260_lm -L $SW_DATA/o2_lbl_uv.nc \
    -np $procs \
     > o2_u260_log
fi
if [ ! -s o2_s260_l ] || [ ! -s $SW_DATA/o2_lbl_sw.nc ] ; then
  echo 'O2 (near-IR)'
  rm -f o2_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_O2 \
    -R 67 260 -c 2500.0 -i 1.0 -l 7 2.3e3 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o o2_s260_l -m o2_s260_lm -L $SW_DATA/o2_lbl_sw.nc \
    -np $procs \
     > o2_s260_log
fi

if [ ! -s so2_s260_l ] || [ ! -s $SW_DATA/so2_lbl_sw.nc ] ; then
  echo 'SO2'
  rm -f so2_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_SO2 \
    -R 215 260 -c 2500.0 -i 1.0 -l 9 3.0e-4 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o so2_s260_l -m so2_s260_lm -L $SW_DATA/so2_lbl_sw.nc \
    -np $procs \
     > so2_s260_log
fi
if [ ! -s so2_u260_l ] || [ ! -s $SW_DATA/so2_lbl_uv.nc ] ; then
  echo 'SO2 (UV)'
  rm -f so2_u260_l*
  Ccorr_k -F $so2_pt_file -X $HITRAN_UV_SO2 \
    -R 1 66 -c 2500.0 -i 1.0 -l 9 3.0e-4 -t 1.0e-3  \
    -s $specfile +S $solspec -q -r $ref_pt_file \
    -o so2_u260_l -m so2_u260_lm -L $SW_DATA/so2_lbl_uv.nc \
    -np $procs \
     > so2_u260_log
fi

if [ ! -s ocs_s260_l ] || [ ! -s $SW_DATA/ocs_lbl_sw.nc ] ; then
  echo 'OCS'
  rm -f ocs_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_OCS \
    -R 215 260 -c 2500.0 -i 1.0 -l 25 1.0e-3 -b 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o ocs_s260_l -m ocs_s260_lm -L $SW_DATA/ocs_lbl_sw.nc \
    -np $procs \
     > ocs_s260_log
fi


# Cloud

if [ ! -s fit_sw_drop5_260 ] ; then
  echo 'Type 5 droplets'
  rm -f mon_sw_drop5_260
  Cscatter_average -s $specfile -P 1 -t -S $solspec \
    -f 5 fit_sw_drop5_260 mon_sw_drop5_260 1.e3 \
    $RAD_DATA/cloud/scatter_drop_type5
fi
if [ ! -s fit_sw_ice8_260 ] ; then
  echo 'Type 8 ice'
  rm -f mon_sw_ice8_260
  Cscatter_average -s $specfile -P 1 -w -S $solspec \
    -f 12 fit_sw_ice8_260 mon_sw_ice8_260 920 \
    $RAD_DATA/cloud/scatter_ice_sw_type8
fi


# Aerosols
echo 'Aerosols'
if [ ! -s soluble_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a soluble_260.avg $RAD_DATA/aerosol/soluble.mon
fi
if [ ! -s dustlike_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dustlike_260.avg $RAD_DATA/aerosol/dustlike.mon
fi
if [ ! -s oceanic_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a oceanic_260.avg $RAD_DATA/aerosol/oceanic.mon
fi
if [ ! -s soot_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a soot_260.avg $RAD_DATA/aerosol/soot.mon
fi
if [ ! -s sulphuric_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a sulphuric_260.avg $RAD_DATA/aerosol/sulphuric.mon
fi
if [ ! -s accumsulp_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a accumsulp_260.avg $RAD_DATA/aerosol/accumsulp.mon
fi
if [ ! -s aitkensulp_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a aitkensulp_260.avg $RAD_DATA/aerosol/aitkensulp.mon
fi
if [ ! -s freshsoot_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a freshsoot_260.avg $RAD_DATA/aerosol/freshsoot.mon
fi
if [ ! -s agedsoot_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a agedsoot_260.avg $RAD_DATA/aerosol/agedsoot.mon
fi
if [ ! -s seasaltfilm_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a seasaltfilm_260.avg $RAD_DATA/aerosol/seasaltfilm.mon
fi
if [ ! -s seasaltjet_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a seasaltjet_260.avg $RAD_DATA/aerosol/seasaltjet.mon
fi
if [ ! -s dust_div1_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div1_260.avg $RAD_DATA/aerosol/dust_div1.mon
fi
if [ ! -s dust_div2_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div2_260.avg $RAD_DATA/aerosol/dust_div2.mon
fi
if [ ! -s dust_div3_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div3_260.avg $RAD_DATA/aerosol/dust_div3.mon
fi
if [ ! -s dust_div4_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div4_260.avg $RAD_DATA/aerosol/dust_div4.mon
fi
if [ ! -s dust_div5_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div5_260.avg $RAD_DATA/aerosol/dust_div5.mon
fi
if [ ! -s dust_div6_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div6_260.avg $RAD_DATA/aerosol/dust_div6.mon
fi
if [ ! -s freshbiomass_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a freshbiomass_260.avg $RAD_DATA/aerosol/freshbiomass.mon
fi
if [ ! -s agedbiomass_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a agedbiomass_260.avg $RAD_DATA/aerosol/agedbiomass.mon
fi
if [ ! -s biogenic_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a biogenic_260.avg $RAD_DATA/aerosol/biogenic.mon
fi
if [ ! -s freshocff_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a freshocff_260.avg $RAD_DATA/aerosol/freshocff.mon
fi
if [ ! -s agedocff_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a agedocff_260.avg $RAD_DATA/aerosol/agedocff.mon
fi
if [ ! -s nitrate_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a nitrate_260.avg $RAD_DATA/aerosol/nitrate.mon
fi
if [ ! -s twobindust_1_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a twobindust_1_260.avg $RAD_DATA/aerosol/twobindust_1.mon
fi
if [ ! -s twobindust_2_260.avg ] ; then
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a twobindust_2_260.avg $RAD_DATA/aerosol/twobindust_2.mon
fi

mv sp_sw_260_jm2 sp_sw_260_jm2_old
mv sp_sw_260_jm2_k sp_sw_260_jm2_old_k
# Construct spectral file
echo 'Constructing spectral file'
prep_spec > prep_spec_260_log << EOF
sp_sw_260_skel
n
sp_sw_260_jm2
5
h2o_v260_l
5
y
h2o_s260_l
9
h2o_s260_s
5
y
co2_s260_l
5
y
o3_u260_l
5
y
o3_s260_l
5
y
n2o_s260_l
5
y
n2o_u260_l
5
y
ch4_s260_l
5
y
o2_j260_l
5
y
o2_s260_l
5
y
so2_s260_l
5
y
so2_u260_l
5
y
ocs_s260_l
10
5
fit_sw_drop5_260
1.50000E-06 5.00000E-05
12
8
fit_sw_ice8_260
11
soluble_260.avg
11
dustlike_260.avg
11
oceanic_260.avg
11
soot_260.avg
11
sulphuric_260.avg
11
accumsulp_260.avg
11
aitkensulp_260.avg
11
freshsoot_260.avg
11
agedsoot_260.avg
11
seasaltfilm_260.avg
11
seasaltjet_260.avg
11
dust_div1_260.avg
11
dust_div2_260.avg
11
dust_div3_260.avg
11
dust_div4_260.avg
11
dust_div5_260.avg
11
dust_div6_260.avg
11
freshbiomass_260.avg
11
agedbiomass_260.avg
11
biogenic_260.avg
11
freshocff_260.avg
11
agedocff_260.avg
11
nitrate_260.avg
11
twobindust_1_260.avg
11
twobindust_2_260.avg
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
echo 'Ordering gases and removing very weak absorbers'
tidy_90 > tidy_260_log <<EOF
sp_sw_260_jm2
o
1
2.5e1
1.0e1
0.1e-1
0.5e-2
0.1e-1
2.3e3
3.0e-2
1.0e-1
0.999990
6
2.5e1
1.0e1
0.1e-1
0.5e-2
0.1e-1
2.3e3
3.0e-6
1.0e-5
-1
EOF

# Add the sub-bands in block 17 using the mappings from the
# major gas k-terms.
# prep_spec >> prep_spec_260_log << EOF
# sp_sw_260_jm2
# a
# 17
# -1
# lean_12
# a
# 0
# 0
# 0
# -1
# EOF

echo -n 'Finished: '; date
exit 0
