.TH Ccdl2cdf 1 "1-9-2006"
.SH NAME
Ccdl2cdf \- Convert CDL input files to netCDF
.SH USAGE
Ccdl2cdf [\fB\-o\fR \fIoutput\-file\fR] \fIinput\-file\fR

Ccdl2cdf \fB\-a\fR \fIbasename\fR

.SH DESCRIPTION
A script to convert CDL input files (readable by l_run_cdl) into netCDF for use with l_run_cdf.

There are two modes of operation as outlined above. Either a single file can be converted, or all files with a given basename.

.SH OPTIONS

.LP

.TP
\fB\-o\fR \fIoutput\-file\fR 
The file name for the output netCDF file. If not given the output file will be called nc_\fIinput\-file\fR. Files will not be overwritten if they already exist.

.TP
\fB\-a\fR \fIbasename\fR
All files \fIbasename\fR.* will be converted to netCDF with output file names nc_\fIbasename\fR.*. In this mode of operation any \fIinput\-file\fR or \fIoutput\-file\fR names given will be ignored.

.SH SEE ALSO
\fBCcdf2cdl\fR(1), \fBncdump\fR(1), \fBncgen\fR(1)

.SH BUGS
Please report bugs to "james.manners@metoffice.gov.uk".

.SH AUTHOR
James Manners, Met. Office, Exeter, UK
