#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Set environment variables
procs=24
. ./env_mars

# HITRAN2020 line data with all 12 isotopes (bespoke par format)
HITRAN_CO2="${ARCHIVE_DATA}/HITRAN2020/co2_111122.bpar"

mkdir -p ${SW_DATA}

if [ ! -s $CO2_LBL_SW ] ; then
  skelfile="${SW_DATA}/sp_sw_276_jm_mars_skel"
  ./mk_sp_sw_276_jm_mars_skel $skelfile > /dev/null
  
  echo "Generating CO2 line absorption data"
  for ((i = 63; i < 277; i++))
  do
    lbl_base="${SW_DATA}/co2_sblbl_s${i}_${PT_FILE}_gf0.9-1.0"
    if [ ! -s ${lbl_base}.nc ] || [ ! -f ${lbl_base}.done ] ; then
      rm -f ${lbl_base}*
      ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} -BD $HITRAN_CO2 \
        -lo 2 -R ${i} ${i} -c 50000.0 -i 0.5 \
        -sb ${GAS_DATA_DIR}/gas_fractions_09_10 -lp 2 \
        -s $skelfile -m ${lbl_base}_lm -L ${lbl_base}.nc \
        -np $procs"
      if command -v sbatch &> /dev/null ; then
        sbatch -W -n $procs -o ${lbl_base}_log -t 360 ${ck_args} &
      else
        ${ck_args} > ${lbl_base}_log
      fi
    fi 
  done

  wait
  echo "Concatenating band data into a single file"
  lblcat $SW_DATA/co2_sblbl_s*_${PT_FILE}_gf0.9-1.0.nc $CO2_LBL_SW
else
  echo "File exists:" $CO2_LBL_SW
fi

# Check job progress using:
# sacct --format=jobname%30,jobid%9,elapsed,totalcpu,ncpus%5,reqmem,exitcode,state
# Use scancel to kill

exit 0
