#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Set environment variables
procs=24
. ./env_mars

# HITRAN2020 data downloaded from hitran.org on 11.11.22
# (No CO2 broadening coefficients are available for H2O.)
HITRAN_H2O="${ARCHIVE_DATA}/HITRAN2020/h2o_111122.par"

# CAVIAR foreign-broadened continuum
CONT_H2O_FRN="${RAD_DATA}/continua/caviar_frn"

mkdir -p ${LW_DATA}

skelfile="${LW_DATA}/sp_lw_400_jm_mars_skel"
./mk_sp_lw_400_jm_mars_skel $skelfile > /dev/null

lbl_base=${H2O_LBL_LWF%.nc}
if [ ! -s ${lbl_base}.nc ] || [ ! -f ${lbl_base}.done ] ; then
  echo "Generating H2O line + foreign continuum absorption data: IR"
  rm -f ${lbl_base}*
  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} -D $HITRAN_H2O \
    -lo 1 -R 1 400 -c 2500.0 -i 0.1 -k -x $CONT_H2O_FRN \
    -s $skelfile -m ${lbl_base}_lm -L ${lbl_base}.nc \
    -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -n $procs -o ${lbl_base}_log -t 360 ${ck_args} &
  else
    ${ck_args} > ${lbl_base}_log
  fi
else
  echo "File exists:" $H2O_LBL_LWF
fi

exit 0
