#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

skelfile=$1
if [ ! -s ${skelfile} ] ; then

# Create skeleton spectral file:
# 276 bands
# 5 gases: H2O (1), CO2 (2), SO2 (9), N2 (13), Ar (37)
# 2 CIA: H2O-H2O, CO2-CO2
# 1 aerosol: sulphuric acid (6)
# Bands specified in microns (u)
prep_spec << EOF > ${skelfile}_log
${skelfile}
276
5
1
2
9
13
37
2
1 1
2 2
1
6
r
u  0.175 0.7  0.005
u  0.7   1.2  0.01
u  1.2   2.4  0.02
u  2.4   3.3  0.05
u  3.3   5.0  0.1
u  5.0   7.0  0.2
u  7.0  10.0  0.5
u 10.0  20.0  1.0
0*276
0*276
n
-1
EOF

fi
exit 0
