#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

skelfile=$1
if [ ! -s ${skelfile} ] ; then

# Create skeleton spectral file:
# 880 bands:
# Band : Wavelength (resolution)
#    1 - 480 : 100.0 nm - 2.5 micron (5nm)
#  481 - 879 : 4000 - 10 cm-1 (10 cm-1)
#  880 - 880 : 10 - 1 cm-1 (9 cm-1)
#
# 5 gases: H2O (1), CO2 (2), SO2 (9), N2 (13), Ar (37)
# 2 CIA: H2O-H2O, CO2-CO2
# 7 aerosols: sulphuric acid (6), Dust Div 1 (17) - Div 6 (22)
#
# Bands specified in microns (u) and cm-1 (c)
prep_spec << EOF > ${skelfile}_log
${skelfile}
880
5
1
2
9
13
37
2
1 1
2 2
7
6
17
18
19
20
21
22
r
u    0.1  2.5 0.005
c 4000.0 10.0 -10.0
c   10.0  1.0  -9.0
0*880
0*880
n
-1
EOF

fi
exit 0
