#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

skelfile=$1
if [ ! -s ${skelfile} ] ; then

# Create skeleton spectral file:
# 400 bands
# 3 gases: H2O (1), CO2 (2), SO2 (9)
# 2 CIA: H2O-H2O, CO2-CO2
# 7 aerosols: sulphuric acid (6), Dust Div 1 (17) - Div 6 (22)
# Bands specified in cm-1 (c)
prep_spec << EOF > ${skelfile}_log
${skelfile}
400
3
1
2
9
2
1 1
2 2
7
6
17
18
19
20
21
22
r
c   1.0   10.0  9.0
c  10.0 4000.0 10.0
0*400
0*400
n
-1
EOF

fi
exit 0
