! *****************************COPYRIGHT*******************************
! (C) Crown copyright Met Office. All rights reserved.
! For further details please refer to the file COPYRIGHT.txt
! which you should have received as part of this distribution.
! *****************************COPYRIGHT*******************************
!
! Module to declare a structure for array dimension data.
!
! Description:
!   This module contains the declaration of the structure
!   used to store array dimension data in the radiation code.
!
!------------------------------------------------------------------------------
MODULE def_dimen

IMPLICIT NONE


TYPE StrDim

  INTEGER :: nd_profile = 1
!   Number of atmospheric profiles
  INTEGER :: nd_layer = 1
!   Number of atmospheric layers
  INTEGER :: nd_layer_clr = 1
!   Number of clear atmospheric layers
  INTEGER :: id_cloud_top = 1
!   Topmost declared cloudy layer
  INTEGER :: nd_2sg_profile = 1
!   Number of flux profiles
  INTEGER :: nd_flux_profile = 1
!   Number of output flux profiles
  INTEGER :: nd_radiance_profile = 1
!   Number of radiance profiles
  INTEGER :: nd_j_profile = 1
!   Number of mean radiance profiles
  INTEGER :: nd_channel = 1
!   Number of spectral channels of output
  INTEGER :: nd_max_order = 1
!   Maximum order of spherical harmonics used
  INTEGER :: nd_direction = 1
!   Number of directions for radiances
  INTEGER :: nd_viewing_level = 1
!   Number levels where the radiance may be calculated
  INTEGER :: nd_sph_coeff = 1
!   Number of spherical coefficients used in determining radiances
  INTEGER :: nd_brdf_basis_fnc = 1
!   Number of BRDF basis functions
  INTEGER :: nd_brdf_trunc = 1
!   Maximum order of BRDF truncation
  INTEGER :: nd_tile_type = 1
!   Number of types of tile
  INTEGER :: nd_aerosol_mode = 1
!   Number of aerosol modes
  INTEGER :: nd_profile_aerosol_prsc = 1
!   Number of profiles of prescribed cloudy optical properties
  INTEGER :: nd_profile_cloud_prsc = 1
!   Number of profiles of prescribed aerosol optical properties
  INTEGER :: nd_opt_level_aerosol_prsc = 1
!   Number of levels of prescribed cloudy optical properties
  INTEGER :: nd_opt_level_cloud_prsc = 1
!   Number of levels of prescribed aerosol optical properties
  INTEGER :: nd_phf_term_aerosol_prsc = 1
!   Number of phase function terms for prescribed aerosol
  INTEGER :: nd_phf_term_cloud_prsc = 1
!   Number of phase function terms for prescribed cloud
  INTEGER :: nd_cloud_component = 1
!   Number of components of clouds.
  INTEGER :: nd_cloud_type = 1
!   Number of permitted types of clouds.
  INTEGER :: nd_cloud_representation = 1
!   Number of permitted representations of clouds.
  INTEGER :: nd_column = 1
!   Number of cloudy subcolumns
  INTEGER :: nd_subcol_gen = 1
!   Number of sub-columns generated by cloud generator
  INTEGER :: nd_subcol_req = 1
!   Number of sub-columns required for sampling
  INTEGER :: nd_overlap_coeff = 1
!   Number of overlap coefficients for cloud
  INTEGER :: nd_source_coeff = 1
!   Number of coefficients for two-stream sources
  INTEGER :: nd_region = 1
!   Number of regions in a layer
  INTEGER :: nd_point_tile = 1
!   Number of points with surface tiling
  INTEGER :: nd_tile = 1
!   Number of tiles
  INTEGER :: nd_k_term_inner = 1
!   Number of k-terms in inner loops

END TYPE StrDim


END MODULE def_dimen
