#!/bin/bash

# This script creates the 6 band SW spectral file sp_sw_ga9

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

if [ ! $SW_DATA ] ; then
  SW_DATA=.
fi

HITRAN_DIR="$RAD_DATA/gases"
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
if [ ! -s $HITRAN_H2O ] ; then
    wget -nc http://www.cfa.harvard.edu/hitran/HITRAN2012/HITRAN2012/By-Molecule/Compressed-files/01_hit12.zip
    unzip 01_hit12.zip -d $HITRAN_DIR
    rm -f 01_hit12.zip
fi

cp $RAD_DATA/spectra/ga7/sp_sw_ga7 .
cp $RAD_DATA/spectra/ga7/sp_sw_ga7_k .
specfile="sp_sw_ga7"
solspec=$RAD_DATA/solar/lean_12
pt_file="$RAD_DATA/gases/pt_ses_new"
ref_pt_file="$RAD_DATA/gases/ref_pt"
procs=24

# H2O
if [ ! -s $SW_DATA/h2o_lbl_swf.nc ] ; then
  echo 'H2O lines and foreign continuum'
  rm -f h2o_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 66 260 -c 2500.0 -i 1.0 -l 1 1.0e2 -b 1.0e-3  \
    -s $RAD_DATA/spectra/ga7_ref/sp_sw_260_jm2 +S $solspec -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_s260_l -m h2o_s260_lm -L $SW_DATA/h2o_lbl_swf.nc \
    -np $procs \
     > h2o_s260_log
fi
if [ ! -s h2o_s6_s ] ; then
  echo 'H2O self-broadened continuum'
  rm -f h2o_s6_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F $pt_file -D $HITRAN_H2O \
    -P 7 -R 3 6 -c 2500.0 -i 1.0 \
    -e $RAD_DATA/continua/elsey_shine_s296 $RAD_DATA/continua/elsey_shine_s260 \
    -k -s $specfile +S $solspec -q -r $ref_pt_file \
    -o h2o_s6_s -m h2o_s6_sm -L $SW_DATA/h2o_lbl_swf.nc \
    -np $procs \
     > h2o_s6_slog
fi


echo 'Aerosols'
rm -f *.avg
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a soluble_6.avg $RAD_DATA/aerosol/soluble.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dustlike_6.avg $RAD_DATA/aerosol/dustlike.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a oceanic_6.avg $RAD_DATA/aerosol/oceanic.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a soot_6.avg $RAD_DATA/aerosol/soot.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a sulphuric_6.avg $RAD_DATA/aerosol/sulphuric.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a accumsulp_6.avg $RAD_DATA/aerosol/accumsulp.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a aitkensulp_6.avg $RAD_DATA/aerosol/aitkensulp.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a freshsoot_bond_6.avg $RAD_DATA/aerosol/freshsoot_bond.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a agedsoot_bond_6.avg $RAD_DATA/aerosol/agedsoot_bond.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a seasaltfilm_6.avg $RAD_DATA/aerosol/seasaltfilm.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a seasaltjet_6.avg $RAD_DATA/aerosol/seasaltjet.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div1_6.avg $RAD_DATA/aerosol/dust_div1.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div2_6.avg $RAD_DATA/aerosol/dust_div2.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div3_6.avg $RAD_DATA/aerosol/dust_div3.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div4_6.avg $RAD_DATA/aerosol/dust_div4.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div5_6.avg $RAD_DATA/aerosol/dust_div5.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div6_6.avg $RAD_DATA/aerosol/dust_div6.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a freshbiomass_bond_6.avg $RAD_DATA/aerosol/freshbiomass_bond.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a agedbiomass_bond_6.avg $RAD_DATA/aerosol/agedbiomass_bond.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a biogenic_6.avg $RAD_DATA/aerosol/biogenic.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a freshocff_6.avg $RAD_DATA/aerosol/freshocff.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a agedocff_6.avg $RAD_DATA/aerosol/agedocff.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a nitrate_6.avg $RAD_DATA/aerosol/nitrate.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a delta_6.avg $RAD_DATA/aerosol/delta.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a twobindust_1_6.avg $RAD_DATA/aerosol/twobindust_1.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a twobindust_2_6.avg $RAD_DATA/aerosol/twobindust_2.mon


echo 'Cloud'
rm -f fit_sw_drop5_6 mon_sw_drop5_6
Cscatter_average -s $specfile -P 1 -t -S $solspec \
  -f 5 fit_sw_drop5_6 mon_sw_drop5_6 1.e3 \
  $RAD_DATA/cloud/scatter_drop_type5


# Construct spectral file
mv sp_sw_ga9 sp_sw_ga9_old 2> /dev/null
mv sp_sw_ga9_k sp_sw_ga9_old_k 2> /dev/null
prep_spec << EOF
sp_sw_ga7
n
sp_sw_ga9
9
y
h2o_s6_s
10
5
y
fit_sw_drop5_6
1.50000E-06 5.00000E-05
12
9
r
12
10
r
11
soluble_6.avg
y
11
dustlike_6.avg
y
11
oceanic_6.avg
y
11
soot_6.avg
y
11
sulphuric_6.avg
y
11
accumsulp_6.avg
y
11
aitkensulp_6.avg
y
11
freshsoot_bond_6.avg
y
11
agedsoot_bond_6.avg
y
11
seasaltfilm_6.avg
y
11
seasaltjet_6.avg
y
11
dust_div1_6.avg
y
11
dust_div2_6.avg
y
11
dust_div3_6.avg
y
11
dust_div4_6.avg
y
11
dust_div5_6.avg
y
11
dust_div6_6.avg
y
11
freshbiomass_bond_6.avg
y
11
agedbiomass_bond_6.avg
y
11
biogenic_6.avg
y
11
freshocff_6.avg
y
11
agedocff_6.avg
y
11
nitrate_6.avg
y
11
delta_6.avg
y
11
twobindust_1_6.avg
y
11
twobindust_2_6.avg
y
-1
EOF

# Construct spectral file
mv sp_sw_ga9c sp_sw_ga9c_old 2> /dev/null
mv sp_sw_ga9c_k sp_sw_ga9c_old_k 2> /dev/null
prep_spec << EOF
sp_sw_ga7
n
sp_sw_ga9c
10
5
y
fit_sw_drop5_6
1.50000E-06 5.00000E-05
12
9
r
12
10
r
-1
EOF

rm *.avg
rm sp_sw_ga7
rm sp_sw_ga7_k
rm -f fit_sw_drop5_6 mon_sw_drop5_6

exit 0
