#!/bin/bash

# This script creates the 260 band SW spectral file sp_sw_260_jm3
# using the same data as the GA9 broadband file.
# GA9 bands  ->  260 bands:
#         1  ->  1/6 -  29
#         2  ->   30 -  66
#         3  ->   67 - 103
#         4  ->  104 - 154
#         5  ->  155 - 214
#         6  ->  215 - 260

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

if [ ! $SW_DATA ] ; then
  SW_DATA=.
fi

HITRAN_DIR="$RAD_DATA/gases"
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
if [ ! -s $HITRAN_H2O ] ; then
    wget -nc http://www.cfa.harvard.edu/hitran/HITRAN2012/HITRAN2012/By-Molecule/Compressed-files/01_hit12.zip
    unzip 01_hit12.zip -d $HITRAN_DIR
    rm -f 01_hit12.zip
fi

cp $RAD_DATA/spectra/ga7_ref/sp_sw_260_jm2 .
cp $RAD_DATA/spectra/ga7_ref/sp_sw_260_jm2_k .
specfile="sp_sw_260_jm2"
solspec=$RAD_DATA/solar/lean_12
pt_file="$RAD_DATA/gases/pt_ses_new"
ref_pt_file="$RAD_DATA/gases/ref_pt"
procs=24

# H2O
if [ ! -s $SW_DATA/h2o_lbl_swf.nc ] ; then
  echo 'H2O lines and foreign continuum'
  rm -f h2o_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 66 260 -c 2500.0 -i 1.0 -l 1 1.0e2 -b 1.0e-3  \
    -s $RAD_DATA/spectra/ga7_ref/sp_sw_260_jm2 +S $solspec -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_s260_l -m h2o_s260_lm -L $SW_DATA/h2o_lbl_swf.nc \
    -np $procs \
     > h2o_s260_log
fi
if [ ! -s h2o_s260_s ] ; then
  echo 'H2O self-broadened continuum'
  rm -f h2o_s260_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F $pt_file -D $HITRAN_H2O \
    -P 7 -R 66 260 -c 2500.0 -i 1.0 \
    -e $RAD_DATA/continua/elsey_shine_s296 $RAD_DATA/continua/elsey_shine_s260 \
    -k -s $specfile +S $solspec -q -r $ref_pt_file \
    -o h2o_s260_s -m h2o_s260_sm -L $SW_DATA/h2o_lbl_swf.nc \
    -np $procs \
     > h2o_s260_slog
fi


# Aerosols
rm -f *.avg
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a soluble_260.avg $RAD_DATA/aerosol/soluble.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dustlike_260.avg $RAD_DATA/aerosol/dustlike.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a oceanic_260.avg $RAD_DATA/aerosol/oceanic.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a soot_260.avg $RAD_DATA/aerosol/soot.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a sulphuric_260.avg $RAD_DATA/aerosol/sulphuric.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a accumsulp_260.avg $RAD_DATA/aerosol/accumsulp.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a aitkensulp_260.avg $RAD_DATA/aerosol/aitkensulp.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a freshsoot_bond_260.avg $RAD_DATA/aerosol/freshsoot_bond.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a agedsoot_bond_260.avg $RAD_DATA/aerosol/agedsoot_bond.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a seasaltfilm_260.avg $RAD_DATA/aerosol/seasaltfilm.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a seasaltjet_260.avg $RAD_DATA/aerosol/seasaltjet.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div1_260.avg $RAD_DATA/aerosol/dust_div1.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div2_260.avg $RAD_DATA/aerosol/dust_div2.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div3_260.avg $RAD_DATA/aerosol/dust_div3.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div4_260.avg $RAD_DATA/aerosol/dust_div4.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div5_260.avg $RAD_DATA/aerosol/dust_div5.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a dust_div6_260.avg $RAD_DATA/aerosol/dust_div6.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a freshbiomass_bond_260.avg $RAD_DATA/aerosol/freshbiomass_bond.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a agedbiomass_bond_260.avg $RAD_DATA/aerosol/agedbiomass_bond.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a biogenic_260.avg $RAD_DATA/aerosol/biogenic.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a freshocff_260.avg $RAD_DATA/aerosol/freshocff.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a agedocff_260.avg $RAD_DATA/aerosol/agedocff.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a nitrate_260.avg $RAD_DATA/aerosol/nitrate.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a twobindust_1_260.avg $RAD_DATA/aerosol/twobindust_1.mon
Cscatter_average -s $specfile -P 1 -w -S $solspec \
  -a twobindust_2_260.avg $RAD_DATA/aerosol/twobindust_2.mon


# Cloud
rm -f fit_sw_drop5_260 mon_sw_drop5_260
Cscatter_average -s $specfile -P 1 -t -S $solspec \
  -f 5 fit_sw_drop5_260 mon_sw_drop5_260 1.e3 \
  $RAD_DATA/cloud/scatter_drop_type5


# Construct spectral file
mv sp_sw_260_jm3 sp_sw_260_jm3_old 2> /dev/null
mv sp_sw_260_jm3_k sp_sw_260_jm3_old_k 2> /dev/null
prep_spec << EOF
sp_sw_260_jm2
n
sp_sw_260_jm3
9
y
h2o_s260_s
10
5
y
fit_sw_drop5_260
1.50000E-06 5.00000E-05
11
soluble_260.avg
y
11
dustlike_260.avg
y
11
oceanic_260.avg
y
11
soot_260.avg
y
11
sulphuric_260.avg
y
11
accumsulp_260.avg
y
11
aitkensulp_260.avg
y
11
freshsoot_bond_260.avg
y
11
agedsoot_bond_260.avg
y
11
seasaltfilm_260.avg
y
11
seasaltjet_260.avg
y
11
dust_div1_260.avg
y
11
dust_div2_260.avg
y
11
dust_div3_260.avg
y
11
dust_div4_260.avg
y
11
dust_div5_260.avg
y
11
dust_div6_260.avg
y
11
freshbiomass_bond_260.avg
y
11
agedbiomass_bond_260.avg
y
11
biogenic_260.avg
y
11
freshocff_260.avg
y
11
agedocff_260.avg
y
11
nitrate_260.avg
y
11
twobindust_1_260.avg
y
11
twobindust_2_260.avg
y
-1
EOF

rm *.avg
rm sp_sw_260_jm2
rm sp_sw_260_jm2_k
rm -f fit_sw_drop5_260 mon_sw_drop5_260

exit 0
