#!/bin/bash

# This script creates a SW spectral file from X-ray to near-IR wavelengths.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

if [ ! $SW_DATA ] ; then
  SW_DATA=.
fi

procs=24
specfile="sp_xsw_photol"
solspec="$RAD_DATA/solar/cmip6_picontrol"

HITRAN_DIR="$RAD_DATA/gases"

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
if [ ! -s $HITRAN_H2O ] ; then
    wget -nc http://www.cfa.harvard.edu/hitran/HITRAN2012/HITRAN2012/By-Molecule/Compressed-files/01_hit12.zip
    unzip 01_hit12.zip -d $HITRAN_DIR
fi

HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
if [ ! -s $HITRAN_CO2 ] ; then
    wget -nc http://www.cfa.harvard.edu/hitran/HITRAN2012/HITRAN2012/By-Molecule/Compressed-files/02_hit12.zip
    unzip 02_hit12.zip -d $HITRAN_DIR
fi

HITRAN_O3="$HITRAN_DIR/03_hit12.par"
if [ ! -s $HITRAN_O3 ] ; then
    wget -nc http://www.cfa.harvard.edu/hitran/HITRAN2012/HITRAN2012/By-Molecule/Compressed-files/03_hit12.zip
    unzip 03_hit12.zip -d $HITRAN_DIR
fi

HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
if [ ! -s $HITRAN_N2O ] ; then
    wget -nc http://www.cfa.harvard.edu/hitran/HITRAN2012/HITRAN2012/By-Molecule/Compressed-files/04_hit08.zip
    unzip 04_hit08.zip -d $HITRAN_DIR
fi

HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
if [ ! -s $HITRAN_CH4 ] ; then
    wget -nc http://www.cfa.harvard.edu/hitran/HITRAN2012/HITRAN2012/By-Molecule/Compressed-files/06_hit12.zip
    unzip 06_hit12.zip -d $HITRAN_DIR
fi

HITRAN_O2="$HITRAN_DIR/07_hit12.par"
if [ ! -s $HITRAN_O2 ] ; then
    wget -nc http://www.cfa.harvard.edu/hitran/HITRAN2012/HITRAN2012/By-Molecule/Compressed-files/07_hit12.zip
    unzip 07_hit12.zip -d $HITRAN_DIR
fi

HITRAN_UV_O3="$RAD_DATA/gases/ser_bdm_o3.xsc"

rm -f ch4.uvxsc
dat2xsc CH4.dat ch4.uvxsc
UV_CH4='ch4.uvxsc' #   6 - 151 nm

rm -f co2.uvxsc
dat2xsc CO2.dat co2.uvxsc
UV_CO2='co2.uvxsc' #   1 - 299 nm

rm -f co.uvxsc
dat2xsc CO.dat co.uvxsc
UV_CO='co.uvxsc'   #   7 - 163 nm

rm -f h2.uvxsc
dat2xsc H2.dat h2.uvxsc
UV_H2='h2.uvxsc'   #   5 - 116 nm

rm -f n2o.uvxsc
dat2xsc N2O.dat n2o.uvxsc
UV_N2O='n2o.uvxsc' #   7 - 249 nm

rm -f no2.uvxsc
dat2xsc NO2.dat no2.uvxsc
UV_NO2='no2.uvxsc' #   7 - 723 nm

rm -f o3.uvxsc
dat2xsc O3.dat o3.uvxsc
UV_O3='o3.uvxsc'   # 186 - 821 nm

rm -f oh.uvxsc
dat2xsc OH.dat oh.uvxsc
UV_OH='oh.uvxsc'   #   5 - 612 nm


rm -f n.uvxsc
dat2xsc N.dat n.uvxsc
UV_N='n.uvxsc' # 0.04 - 102.7 nm

rm -f o.uvxsc
dat2xsc O.dat o.uvxsc
UV_O='o.uvxsc' # 0.04 - 102.7 nm

rm -f o2_hires.uvxsc
dat2xsc O2.dat o2_hires.uvxsc
UV_O2_HIRES='o2_hires.uvxsc' # 0.04 - 294 nm

rm -f n2_hires.uvxsc
dat2xsc N2.dat n2_hires.uvxsc
UV_N2_HIRES='n2_hires.uvxsc' # 0.04 - 102.7 nm

rm -f h2o_jpl.uvxsc
dat2xsc H2O.dat h2o_jpl.uvxsc
UV_H2O='h2o_jpl.uvxsc' #   7 - 198 nm

pt_uv='pt_single'
pt_file="$RAD_DATA/gases/pt_ses_new"
o3_pt_file="$RAD_DATA/gases/pt_o3_ser"
o2_pt_file="$RAD_DATA/gases/pt_o2_jpl"
n2o_pt_file="$RAD_DATA/gases/pt_n2o_uv"
so2_pt_file="$RAD_DATA/gases/pt_so2_uv"
ref_pt_file="$RAD_DATA/gases/ref_pt"

# Create skeleton spectral file
skelfile="sp_xsw_skel"
rm -f $skelfile
. mk_sp_xsw_skel > /dev/null

# Gases

## # Methane (CH4)
## if [ ! -s ch4_xuv10_l ] || [ ! -s $SW_DATA/ch4_lbl_xuv10.nc ] ; then
##   echo 'CH4 (XUV continuum)'
##   rm -f ch4_xuv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_CH4 \
##     -R 1 1 -i 100.0 -l 6 1.0e-2 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o ch4_xuv10_l -m ch4_xuv10_lm -L $SW_DATA/ch4_lbl_xuv10.nc -np $procs \
##      > ch4_xuv10_log
## fi
## if [ ! -s ch4_euv10_l ] || [ ! -s $SW_DATA/ch4_lbl_euv10.nc ] ; then
##   echo 'CH4 (EUV continuum)'
##   rm -f ch4_euv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_CH4 \
##     -R 2 2 -i 10.0 -l 6 1.0e-2 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o ch4_euv10_l -m ch4_euv10_lm -L $SW_DATA/ch4_lbl_euv10.nc -np $procs \
##      > ch4_euv10_log
## fi
## if [ ! -s ch4_uv10_l ] || [ ! -s $SW_DATA/ch4_lbl_uv10.nc ] ; then
##   echo 'CH4 (UV continuum)'
##   rm -f ch4_uv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_CH4 \
##     -R 3 4 -i 1.0 -l 6 1.0e-2 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o ch4_uv10_l -m ch4_uv10_lm -L $SW_DATA/ch4_lbl_uv10.nc -np $procs \
##      > ch4_uv10_log
## fi
## 
## # Carbon Dioxide (CO2)
## if [ ! -s co2_xuv10_l ] || [ ! -s $SW_DATA/co2_lbl_xuv10.nc ] ; then
##   echo 'CO2 (XUV continuum)'
##   rm -f co2_xuv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_CO2 \
##     -R 1 9 -i 100.0 -l 2 1.0e1 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o co2_xuv10_l -m co2_xuv10_lm -L $SW_DATA/co2_lbl_xuv10.nc -np $procs \
##      > co2_xuv10_log
## fi
## if [ ! -s co2_euv10_l ] || [ ! -s $SW_DATA/co2_lbl_euv10.nc ] ; then
##   echo 'CO2 (EUV continuum)'
##   rm -f co2_euv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_CO2 \
##     -R 10 99 -i 10.0 -l 2 1.0e1 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o co2_euv10_l -m co2_euv10_lm -L $SW_DATA/co2_lbl_euv10.nc -np $procs \
##      > co2_euv10_log
## fi
## if [ ! -s co2_uv10_l ] || [ ! -s $SW_DATA/co2_lbl_uv10.nc ] ; then
##   echo 'CO2 (UV continuum)'
##   rm -f co2_uv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_CO2 \
##     -R 100 299 -i 1.0 -l 2 1.0e1 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o co2_uv10_l -m co2_uv10_lm -L $SW_DATA/co2_lbl_uv10.nc -np $procs \
##      > co2_uv10_log
## fi
## 
## # Carbon Monoxide (CO)
## if [ ! -s co_xuv10_l ] || [ ! -s $SW_DATA/co_lbl_xuv10.nc ] ; then
##   echo 'CO (XUV continuum)'
##   rm -f co_xuv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_CO \
##     -R 7 9 -i 100.0 -l 5 2.0e-3 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o co_xuv10_l -m co_xuv10_lm -L $SW_DATA/co_lbl_xuv10.nc -np $procs \
##      > co_xuv10_log
## fi
## if [ ! -s co_euv10_l ] || [ ! -s $SW_DATA/co_lbl_euv10.nc ] ; then
##   echo 'CO (EUV continuum)'
##   rm -f co_euv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_CO \
##     -R 10 99 -i 10.0 -l 5 2.0e-3 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o co_euv10_l -m co_euv10_lm -L $SW_DATA/co_lbl_euv10.nc -np $procs \
##      > co_euv10_log
## fi
## if [ ! -s co_uv10_l ] || [ ! -s $SW_DATA/co_lbl_uv10.nc ] ; then
##   echo 'CO (UV continuum)'
##   rm -f co_uv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_CO \
##     -R 100 163 -i 1.0 -l 5 2.0e-3 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o co_uv10_l -m co_uv10_lm -L $SW_DATA/co_lbl_uv10.nc -np $procs \
##      > co_uv10_log
## fi
## 
## # Hydrogen (H2)
## if [ ! -s h2_xuv10_l ] || [ ! -s $SW_DATA/h2_lbl_xuv10.nc ] ; then
##   echo 'H2 (XUV continuum)'
##   rm -f h2_xuv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_H2 \
##     -R 5 9 -i 100.0 -l 23 5.0e-4 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o h2_xuv10_l -m h2_xuv10_lm -L $SW_DATA/h2_lbl_xuv10.nc -np $procs \
##      > h2_xuv10_log
## fi
## if [ ! -s h2_euv10_l ] || [ ! -s $SW_DATA/h2_lbl_euv10.nc ] ; then
##   echo 'H2 (EUV continuum)'
##   rm -f h2_euv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_H2 \
##     -R 10 99 -i 10.0 -l 23 5.0e-4 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o h2_euv10_l -m h2_euv10_lm -L $SW_DATA/h2_lbl_euv10.nc -np $procs \
##      > h2_euv10_log
## fi
## if [ ! -s h2_uv10_l ] || [ ! -s $SW_DATA/h2_lbl_uv10.nc ] ; then
##   echo 'H2 (UV continuum)'
##   rm -f h2_uv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_H2 \
##     -R 100 116 -i 1.0 -l 23 5.0e-4 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o h2_uv10_l -m h2_uv10_lm -L $SW_DATA/h2_lbl_uv10.nc -np $procs \
##      > h2_uv10_log
## fi

## # Dinitrogen Oxide (N2O)
## if [ ! -s n2o_xuv10_l ] || [ ! -s $SW_DATA/n2o_lbl_xuv10.nc ] ; then
##   echo 'N2O (XUV continuum)'
##   rm -f n2o_xuv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_N2O \
##     -R 7 9 -i 100.0 -l 4 5.0e-3 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o n2o_xuv10_l -m n2o_xuv10_lm -L $SW_DATA/n2o_lbl_xuv10.nc -np $procs \
##      > n2o_xuv10_log
## fi
## if [ ! -s n2o_euv10_l ] || [ ! -s $SW_DATA/n2o_lbl_euv10.nc ] ; then
##   echo 'N2O (EUV continuum)'
##   rm -f n2o_euv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_N2O \
##     -R 10 99 -i 10.0 -l 4 5.0e-3 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o n2o_euv10_l -m n2o_euv10_lm -L $SW_DATA/n2o_lbl_euv10.nc -np $procs \
##      > n2o_euv10_log
## fi
## if [ ! -s n2o_uv10_l ] || [ ! -s $SW_DATA/n2o_lbl_uv10.nc ] ; then
##   echo 'N2O (UV continuum)'
##   rm -f n2o_uv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_N2O \
##     -R 100 249 -i 1.0 -l 4 5.0e-3 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o n2o_uv10_l -m n2o_uv10_lm -L $SW_DATA/n2o_lbl_uv10.nc -np $procs \
##      > n2o_uv10_log
## fi
## 
## # Nitrogen Dioxide (NO2)
## if [ ! -s no2_xuv10_l ] || [ ! -s $SW_DATA/no2_lbl_xuv10.nc ] ; then
##   echo 'NO2 (XUV continuum)'
##   rm -f no2_xuv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_NO2 \
##     -R 7 9 -i 100.0 -l 10 5.0e-4 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o no2_xuv10_l -m no2_xuv10_lm -L $SW_DATA/no2_lbl_xuv10.nc -np $procs \
##      > no2_xuv10_log
## fi
## if [ ! -s no2_euv10_l ] || [ ! -s $SW_DATA/no2_lbl_euv10.nc ] ; then
##   echo 'NO2 (EUV continuum)'
##   rm -f no2_euv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_NO2 \
##     -R 10 99 -i 10.0 -l 10 5.0e-4 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o no2_euv10_l -m no2_euv10_lm -L $SW_DATA/no2_lbl_euv10.nc -np $procs \
##      > no2_euv10_log
## fi
## if [ ! -s no2_uv10_l ] || [ ! -s $SW_DATA/no2_lbl_uv10.nc ] ; then
##   echo 'NO2 (UV continuum)'
##   rm -f no2_uv10_l*
##   Ccorr_k -F $pt_uv -UVX $UV_NO2 \
##     -R 100 320 -i 1.0 -l 10 5.0e-4 -t 1.0e-3  \
##     -s $skelfile +S $solspec \
##     -o no2_uv10_l -m no2_uv10_lm -L $SW_DATA/no2_lbl_uv10.nc -np $procs \
##      > no2_uv10_log
## fi

# Nitrogen (N2)
if [ ! -s n2_xuv_x_l ] || [ ! -s $SW_DATA/n2_lbl_xuv_x.nc ] ; then
  echo 'N2 (XUV continuum)'
  rm -f n2_xuv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_N2_HIRES \
    -R 1 5 -i 1000.0 -l 13 7.5e3 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o n2_xuv_x_l -m n2_xuv_x_lm -L $SW_DATA/n2_lbl_xuv_x.nc -np $procs \
     > n2_xuv_x_log
fi
if [ ! -s n2_euv_x_l ] || [ ! -s $SW_DATA/n2_lbl_euv_x.nc ] ; then
  echo 'N2 (EUV continuum)'
  rm -f n2_euv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_N2_HIRES \
    -R 6 14 -i 10.0 -l 13 7.5e3 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o n2_euv_x_l -m n2_euv_x_lm -L $SW_DATA/n2_lbl_euv_x.nc -np $procs \
     > n2_euv_x_log
fi

# Oxygen (O2)
if [ ! -s o2_xuv_x_l ] || [ ! -s $SW_DATA/o2_lbl_xuv_x.nc ] ; then
  echo 'O2 (XUV continuum)'
  rm -f o2_xuv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_O2_HIRES \
    -R 1 5 -i 1000.0 -l 7 2.3e3 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o o2_xuv_x_l -m o2_xuv_x_lm -L $SW_DATA/o2_lbl_xuv_x.nc -np $procs \
     > o2_xuv_x_log
fi
if [ ! -s o2_euv_x_l ] || [ ! -s $SW_DATA/o2_lbl_euv_x.nc ] ; then
  echo 'O2 (EUV continuum)'
  rm -f o2_euv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_O2_HIRES \
    -R 6 14 -i 10.0 -l 7 2.3e3 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o o2_euv_x_l -m o2_euv_x_lm -L $SW_DATA/o2_lbl_euv_x.nc -np $procs \
     > o2_euv_x_log
fi
if [ ! -s o2_uv_x_l ] || [ ! -s $SW_DATA/o2_lbl_uv_x.nc ] ; then
  echo 'O2 (UV continuum)'
  rm -f o2_uv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_O2_HIRES \
    -R 15 20 -i 1.0 -l 7 2.3e3 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o o2_uv_x_l -m o2_uv_x_lm -L $SW_DATA/o2_lbl_uv_x.nc -np $procs \
     > o2_uv_x_log
fi

# Ozone (O3)
if [ ! -s o3_uv_x_l ] || [ ! -s $SW_DATA/o3_lbl_uv_x.nc ] ; then
  echo 'O3 (UV continuum)'
  rm -f o3_uv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_O3 \
    -R 17 17 -i 1.0 -l 3 1.0e-2 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o o3_uv_x_l -m o3_uv_x_lm -L $SW_DATA/o3_lbl_uv_x.nc -np $procs \
     > o3_uv_x_log
fi
if [ ! -s o3_nuv_x_l ] ; then
  echo 'O3 (NUV continuum)'
  rm -f o3_nuv_x_l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R 18 21 -i 1.0 -l 3 1.0e-2 -t 1.0e-2  \
    -s $skelfile +S $solspec -q -r $ref_pt_file \
    -o o3_nuv_x_l -m o3_nuv_x_lm -L $SW_DATA/o3_lbl_nuv_x.nc -np $procs \
    > o3_nuv_x_log
fi
if [ ! -s o3_uva_x_l ] ; then
  echo 'O3 (UVA continuum)'
  rm -f o3_uva_x_l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R 22 22 -i 1.0 -l 3 1.0e-2 -n 2  \
    -s $skelfile +S $solspec -q -r $ref_pt_file \
    -o o3_uva_x_l -m o3_uva_x_lm -L $SW_DATA/o3_lbl_uva_x.nc -np $procs \
    > o3_uva_x_log
fi
if [ ! -s o3_vis_x_l ] ; then
  echo 'O3 (visible continuum)'
  rm -f o3_vis_x_l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R 23 24 -i 1.0 -l 3 1.0e-2 -t 1.0e-2  \
    -s $skelfile +S $solspec -q -r $ref_pt_file \
    -o o3_vis_x_l -m o3_vis_x_lm -L $SW_DATA/o3_lbl_vis_x.nc -np $procs \
    > o3_vis_x_log
fi
if [ ! -s o3_x_l ] ; then
  echo 'O3 (lines)'
  rm -f o3_x_l*
  Ccorr_k -F $pt_file -D $HITRAN_O3 \
    -R 26 26 -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-2  \
    -s $skelfile +S $solspec -lk \
    -o o3_x_l -m o3_x_lm -L $SW_DATA/o3_lbl_xsw.nc -np $procs \
    > o3_x_log
fi

# Atomic Oxygen (O)
if [ ! -s o_xuv_x_l ] || [ ! -s $SW_DATA/o_lbl_xuv_x.nc ] ; then
  echo 'O (XUV continuum)'
  rm -f o_xuv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_O \
    -R 1 5 -i 1000.0 -l 39 2.6e-4 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o o_xuv_x_l -m o_xuv_x_lm -L $SW_DATA/o_lbl_xuv_x.nc -np $procs \
     > o_xuv_x_log
fi
if [ ! -s o_euv_x_l ] || [ ! -s $SW_DATA/o_lbl_euv_x.nc ] ; then
  echo 'O (EUV continuum)'
  rm -f o_euv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_O \
    -R 6 12 -i 10.0 -l 39 2.6e-4 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o o_euv_x_l -m o_euv_x_lm -L $SW_DATA/o_lbl_euv_x.nc -np $procs \
     > o_euv_x_log
fi

# Atomic Nitrogen (N)
if [ ! -s n_xuv_x_l ] || [ ! -s $SW_DATA/n_lbl_xuv_x.nc ] ; then
  echo 'N (XUV continuum)'
  rm -f n_xuv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_N \
    -R 1 5 -i 1000.0 -l 40 3.0e-10 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o n_xuv_x_l -m n_xuv_x_lm -L $SW_DATA/n_lbl_xuv_x.nc -np $procs \
     > n_xuv_x_log
fi
if [ ! -s n_euv_x_l ] || [ ! -s $SW_DATA/n_lbl_euv_x.nc ] ; then
  echo 'N (EUV continuum)'
  rm -f n_euv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_N \
    -R 6 12 -i 10.0 -l 40 3.0e-10 -t 1.0e-2  \
    -s $skelfile +S $solspec \
    -o n_euv_x_l -m n_euv_x_lm -L $SW_DATA/n_lbl_euv_x.nc -np $procs \
     > n_euv_x_log
fi

# Water vapour (H2O)
if [ ! -s h2o_xuv_x_l ] || [ ! -s $SW_DATA/h2o_lbl_xuv_x.nc ] ; then
  echo 'H2O (XUV continuum)'
  rm -f h2o_xuv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_H2O \
    -R 5 5 -i 1000.0 -l 1 1.0e-5 -t 1.0e-3  \
    -s $skelfile +S $solspec \
    -o h2o_xuv_x_l -m h2o_xuv_x_lm -L $SW_DATA/h2o_lbl_xuv_x.nc \
    -np $procs \
     > h2o_xuv_x_log
fi
if [ ! -s h2o_euv_x_l ] || [ ! -s $SW_DATA/h2o_lbl_euv_x.nc ] ; then
  echo 'H2O (EUV continuum)'
  rm -f h2o_euv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_H2O \
    -R 6 14 -i 10.0 -l 1 1.0e-5 -t 1.0e-3  \
    -s $skelfile +S $solspec \
    -o h2o_euv_x_l -m h2o_euv_x_lm -L $SW_DATA/h2o_lbl_euv_x.nc \
    -np $procs \
     > h2o_euv_x_log
fi
if [ ! -s h2o_fuv_x_l ] || [ ! -s $SW_DATA/h2o_lbl_fuv_x.nc ] ; then
  echo 'H2O (FUV continuum)'
  rm -f h2o_fuv_x_l*
  Ccorr_k -F $pt_uv -UVX $UV_H2O \
    -R 15 17 -i 1.0 -l 1 1.0e-5 -t 1.0e-3  \
    -s $skelfile +S $solspec \
    -o h2o_fuv_x_l -m h2o_fuv_x_lm -L $SW_DATA/h2o_lbl_fuv_x.nc \
    -np $procs \
     > h2o_fuv_x_log
fi
if [ ! -s $SW_DATA/h2o_lbl_swf.nc ] ; then
  echo 'H2O lines'
  rm -f h2o_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 66 260 -c 2500.0 -i 1.0 -l 1 1.0e2 -b 1.0e-3  \
    -s $RAD_DATA/spectra/ga7_ref/sp_sw_260_jm2 +S $solspec -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_s260_l -m h2o_s260_lm -L $SW_DATA/h2o_lbl_swf.nc \
    -np $procs \
     > h2o_s260_log
fi
if [ ! -s h2o_x_23l ] ; then
  echo 'H2O band 23'
  rm -f h2o_x_23l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 23 23 -c 2500.0 -i 1.0 -l 1 1.0e2 -n 2  \
    -s $skelfile +S $solspec -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_x_23l -m h2o_x_23lm -L $SW_DATA/h2o_lbl_swf.nc
fi
if [ ! -s h2o_x_24l ] ; then
  echo 'H2O band 24'
  rm -f h2o_x_24l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 24 24 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 1.0e-2  \
    -s $skelfile +S $solspec -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_x_24l -m h2o_x_24lm -L $SW_DATA/h2o_lbl_swf.nc
fi
if [ ! -s h2o_x_25l ] ; then
  echo 'H2O band 25'
  rm -f h2o_x_25l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 25 25 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 1.0e-2  \
    -s $skelfile +S $solspec -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_x_25l -m h2o_x_25lm -L $SW_DATA/h2o_lbl_swf.nc
fi
if [ ! -s h2o_x_26l ] ; then
  echo 'H2O band 26'
  rm -f h2o_x_26l*
  Ccorr_k -F $pt_file -D $HITRAN_H2O \
    -R 26 26 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 1.2e-2  \
    -s $skelfile +S $solspec -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o h2o_x_26l -m h2o_x_26lm -L $SW_DATA/h2o_lbl_swf.nc
fi

if [ ! -s h2o_x_s ] ; then
  echo 'H2O self-broadened continuum'
  rm -f h2o_x_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F $pt_file -D $HITRAN_H2O \
    -P 7 -R 23 26 -c 2500.0 -i 1.0 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $skelfile +S $solspec -q -r $ref_pt_file \
    -o h2o_x_s -m h2o_x_sm -L $SW_DATA/h2o_lbl_swf.nc
fi

if [ ! -s $SW_DATA/co2_lbl_sw.nc ] ; then
  echo 'CO2 lines'
  rm -f co2_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 104 260 -c 2500.0 -i 1.0 -l 2 1.0e1 -b 1.0e-3  \
    -s $RAD_DATA/spectra/ga7_ref/sp_sw_260_jm2 +S $solspec -lk \
    -o co2_s260_l -m co2_s260_lm -L $SW_DATA/co2_lbl_sw.nc \
    -np $procs \
     > co2_s260_log
fi
if [ ! -s co2_x_25l ] ; then
  echo 'CO2 band 25'
  rm -f co2_x_25l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 25 25 -c 2500.0 -i 1.0 -l 2 1.0e1 -t 4.0e-3  \
    -s $skelfile +S $solspec -lk \
    -o co2_x_25l -m co2_x_25lm -L $SW_DATA/co2_lbl_sw.nc
fi
if [ ! -s co2_x_26l ] ; then
  echo 'CO2 band 26'
  rm -f co2_x_26l*
  Ccorr_k -F $pt_file -D $HITRAN_CO2 \
    -R 26 26 -c 2500.0 -i 1.0 -l 2 1.0e1 -t 1.0e-2  \
    -s $skelfile +S $solspec -lk \
    -o co2_x_26l -m co2_x_26lm -L $SW_DATA/co2_lbl_sw.nc
fi

if [ ! -s n2o_x_26l ] ; then
  echo 'N2O'
  rm -f n2o_x_26l*
  Ccorr_k -F $pt_file -D $HITRAN_N2O \
    -R 26 26 -c 2500.0 -i 1.0 -l 4 5.0e-3 -t 6.0e-3  \
    -s $skelfile +S $solspec -lk \
    -o n2o_x_26l -m n2o_x_26lm -L $SW_DATA/n2o_lbl_xsw.nc
fi

if [ ! -s $SW_DATA/ch4_lbl_sw.nc ] ; then
  echo 'CH4 lines'
  rm -f ch4_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_CH4 \
    -R 104 260 -c 2500.0 -i 1.0 -l 6 1.0e-2 -b 1.0e-3  \
    -s $RAD_DATA/spectra/ga7_ref/sp_sw_260_jm2 +S $solspec -lk \
    -o ch4_s260_l -m ch4_s260_lm -L $SW_DATA/ch4_lbl_sw.nc \
    -np $procs \
     > ch4_s260_log
fi
if [ ! -s ch4_x_25l ] ; then
  echo 'CH4 band 25'
  rm -f ch4_x_25l*
  Ccorr_k -F $pt_file -D $HITRAN_CH4 \
    -R 25 25 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3  \
    -s $skelfile +S $solspec -lk \
    -o ch4_x_25l -m ch4_x_25lm -L $SW_DATA/ch4_lbl_sw.nc
fi
if [ ! -s ch4_x_26l ] ; then
  echo 'CH4 band 26'
  rm -f ch4_x_26l*
  Ccorr_k -F $pt_file -D $HITRAN_CH4 \
    -R 26 26 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3  \
    -s $skelfile +S $solspec -lk \
    -o ch4_x_26l -m ch4_x_26lm -L $SW_DATA/ch4_lbl_sw.nc
fi

if [ ! -s $SW_DATA/o2_lbl_sw.nc ] ; then
  echo 'O2 lines'
  rm -f o2_s260_l*
  Ccorr_k -F $pt_file -D $HITRAN_O2 \
    -R 67 260 -c 2500.0 -i 1.0 -l 7 2.3e3 -b 1.0e-3  \
    -s $RAD_DATA/spectra/ga7_ref/sp_sw_260_jm2 +S $solspec -lk \
    -o o2_s260_l -m o2_s260_lm -L $SW_DATA/o2_lbl_sw.nc \
    -np $procs \
     > o2_s260_log
fi
if [ ! -s o2_x_23l ] ; then
  echo 'O2 band 23'
  rm -f o2_x_23l*
  Ccorr_k -F $pt_file -D $HITRAN_O2 \
    -R 23 23 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2  \
    -s $skelfile +S $solspec -lk \
    -o o2_x_23l -m o2_x_23lm -L $SW_DATA/o2_lbl_sw.nc
fi
if [ ! -s o2_x_24l ] ; then
  echo 'O2 band 24'
  rm -f o2_x_24l*
  Ccorr_k -F $pt_file -D $HITRAN_O2 \
    -R 24 24 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 2.2e-3  \
    -s $skelfile +S $solspec -lk \
    -o o2_x_24l -m o2_x_24lm -L $SW_DATA/o2_lbl_sw.nc
fi
if [ ! -s o2_x_25l ] ; then
  echo 'O2 band 25'
  rm -f o2_x_25l*
  Ccorr_k -F $pt_file -D $HITRAN_O2 \
    -R 25 25 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2  \
    -s $skelfile +S $solspec -lk \
    -o o2_x_25l -m o2_x_25lm -L $SW_DATA/o2_lbl_sw.nc
fi


# Cloud

if [ ! -s fit_sw_drop5_26 ] ; then
  rm -f mon_sw_drop5_26
  Cscatter_average -s $skelfile -P 1 -t -S $solspec \
    -f 5 fit_sw_drop5_26 mon_sw_drop5_26 1.e3 \
    $RAD_DATA/cloud/scatter_drop_sw_type5
fi
if [ ! -s fit_sw_ice8_26 ] ; then
  rm -f mon_sw_ice8_26
  Cscatter_average -s $skelfile -P 1 -w -S $solspec \
    -f 12 fit_sw_ice8_26 mon_sw_ice8_26 920 \
    $RAD_DATA/cloud/scatter_ice_sw_type8
fi


# Aerosols

if [ ! -s soluble_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a soluble_26.avg $RAD_DATA/aerosol/soluble.mon
fi
if [ ! -s dustlike_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a dustlike_26.avg $RAD_DATA/aerosol/dustlike.mon
fi
if [ ! -s oceanic_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a oceanic_26.avg $RAD_DATA/aerosol/oceanic.mon
fi
if [ ! -s soot_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a soot_26.avg $RAD_DATA/aerosol/soot.mon
fi
if [ ! -s sulphuric_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a sulphuric_26.avg $RAD_DATA/aerosol/sulphuric.mon
fi
if [ ! -s accumsulp_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a accumsulp_26.avg $RAD_DATA/aerosol/accumsulp.mon
fi
if [ ! -s aitkensulp_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a aitkensulp_26.avg $RAD_DATA/aerosol/aitkensulp.mon
fi
if [ ! -s freshsoot_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a freshsoot_26.avg $RAD_DATA/aerosol/freshsoot.mon
fi
if [ ! -s agedsoot_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a agedsoot_26.avg $RAD_DATA/aerosol/agedsoot.mon
fi
if [ ! -s seasaltfilm_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a seasaltfilm_26.avg $RAD_DATA/aerosol/seasaltfilm.mon
fi
if [ ! -s seasaltjet_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a seasaltjet_26.avg $RAD_DATA/aerosol/seasaltjet.mon
fi
if [ ! -s dust_div1_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a dust_div1_26.avg $RAD_DATA/aerosol/dust_div1.mon
fi
if [ ! -s dust_div2_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a dust_div2_26.avg $RAD_DATA/aerosol/dust_div2.mon
fi
if [ ! -s dust_div3_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a dust_div3_26.avg $RAD_DATA/aerosol/dust_div3.mon
fi
if [ ! -s dust_div4_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a dust_div4_26.avg $RAD_DATA/aerosol/dust_div4.mon
fi
if [ ! -s dust_div5_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a dust_div5_26.avg $RAD_DATA/aerosol/dust_div5.mon
fi
if [ ! -s dust_div6_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a dust_div6_26.avg $RAD_DATA/aerosol/dust_div6.mon
fi
if [ ! -s freshbiomass_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a freshbiomass_26.avg $RAD_DATA/aerosol/freshbiomass.mon
fi
if [ ! -s agedbiomass_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a agedbiomass_26.avg $RAD_DATA/aerosol/agedbiomass.mon
fi
if [ ! -s biogenic_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a biogenic_26.avg $RAD_DATA/aerosol/biogenic.mon
fi
if [ ! -s freshocff_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a freshocff_26.avg $RAD_DATA/aerosol/freshocff.mon
fi
if [ ! -s agedocff_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a agedocff_26.avg $RAD_DATA/aerosol/agedocff.mon
fi
if [ ! -s nitrate_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a nitrate_26.avg $RAD_DATA/aerosol/nitrate.mon
fi
if [ ! -s twobindust_1_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a twobindust_1_26.avg $RAD_DATA/aerosol/twobindust_1.mon
fi
if [ ! -s twobindust_2_26.avg ] ; then
Cscatter_average -s $skelfile -P 1 -w -S $solspec \
  -a twobindust_2_26.avg $RAD_DATA/aerosol/twobindust_2.mon
fi

mv ${specfile} ${specfile}_old
mv ${specfile}_k ${specfile}_old_k
# Construct spectral file
prep_spec << EOF
${skelfile}
n
${specfile}
2
n
${solspec}
y
3
a
5
h2o_xuv_x_l
5
y
h2o_euv_x_l
5
y
h2o_fuv_x_l
5
y
h2o_x_24l
5
y
h2o_x_25l
5
y
h2o_x_26l
9
h2o_x_s
5
y
co2_x_25l
5
y
co2_x_26l
5
y
o2_xuv_x_l
5
y
o2_euv_x_l
5
y
o2_uv_x_l
5
y
o3_uv_x_l
5
y
o3_nuv_x_l
5
y
o3_uva_x_l
5
y
o3_vis_x_l
5
y
o3_x_l
5
y
h2o_x_23l
5
y
n2o_x_26l
5
y
ch4_x_25l
5
y
ch4_x_26l
5
y
o2_x_23l
5
y
o2_x_24l
5
y
o2_x_25l
5
y
n2_xuv_x_l
5
y
n2_euv_x_l
5
y
o_xuv_x_l
5
y
o_euv_x_l
5
y
n_xuv_x_l
5
y
n_euv_x_l
10
5
fit_sw_drop5_26
1.50000E-06 5.00000E-05
12
8
fit_sw_ice8_26
7.00000E-06 3.20000E-04
11
soluble_26.avg
11
dustlike_26.avg
11
oceanic_26.avg
11
soot_26.avg
11
sulphuric_26.avg
11
accumsulp_26.avg
11
aitkensulp_26.avg
11
freshsoot_26.avg
11
agedsoot_26.avg
11
seasaltfilm_26.avg
11
seasaltjet_26.avg
11
dust_div1_26.avg
11
dust_div2_26.avg
11
dust_div3_26.avg
11
dust_div4_26.avg
11
dust_div5_26.avg
11
dust_div6_26.avg
11
freshbiomass_26.avg
11
agedbiomass_26.avg
11
biogenic_26.avg
11
freshocff_26.avg
11
agedocff_26.avg
11
nitrate_26.avg
11
twobindust_1_26.avg
11
twobindust_2_26.avg
-1
EOF

# Column ammounts integrated down to  stratopause  |  mesopause
# Column amount for Water Vapour      0.156458E-04    0.630611E-08
# Column amount for Carbon Dioxide    0.251123E-02    0.708379E-05
# Column amount for Ozone             0.784418E-05    0.128860E-07
# Column amount for Dinitrogen Oxide  0.138654E-07    0.103199E-10
# Column amount for Carbon monoxide   0.112071E-05    0.208955E-06
# Column amount for Methane           0.399384E-06    0.123864E-08
# Column amount for Oxygen            0.107215E+01    0.332647E-02
# Column amount for Nitrogen monoxide 0.834753E-07    0.249072E-07
# Column amount for Nitrogen dioxide  0.205777E-08    0.482538E-11
# Column amount for Nitrogen          0.351191E+01    0.130265E-01
# Column amount for Hydrogen          0.0             0.0
# Column amount for Atomic Oxygen     0.262064E-03    0.228072E-03
# Column amount for Atomic Nitrogen   0.299410E-09    0.260047E-09
tidy_90 <<EOF
${specfile}
o
6
0.156458E-04
0.708379E-05
0.128860E-07
0.103199E-10
0.208955E-06
0.123864E-08
0.332647E-02
0.249072E-07
0.482538E-11
0.130265E+00
0.0         
0.228072E-03
0.260047E-09
-1
EOF

prep_spec << EOF
${specfile}
a
17
2
3
4
5
11
12
13
14
15
16
17
21
22
0
${solspec}
a
0
0
0
20
7
1
n
O2_1.qy
O2_1.pe
20
y
7
2
n
O2_2.qy
O2_2.pe
20
y
7
6
n
O2_6.qy
O2_6.pe
20
y
7
7
y
O2_7.qy
O2_7.pe
20
y
13
1
y
N2_1.qy
N2_1.pe
20
y
13
2
y
N2_2.qy
N2_2.pe
20
y
13
3
y
N2_3.qy
N2_3.pe
20
y
39
1
y
O_1.qy
O_1.pe
20
y
39
2
y
O_2.qy
O_2.pe
20
y
39
3
y
O_3.qy
O_3.pe
20
y
39
4
y
O_4.qy
O_4.pe
20
y
39
5
y
O_5.qy
O_5.pe
20
y
40
1
y
N_1.qy
N_1.pe
20
y
1
2
n
H2O_2.qy

20
y
1
3
n
H2O_3.qy

20
y
1
5
n
H2O_5.qy

20
y
3
1
y
O3_1.qy

20
y
3
4
y
O3_4.qy

-1
EOF

exit 0
