#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

if [ ! $SW_DATA ] ; then
  SW_DATA=.
fi

NUM_THREADS=4
specfile="sp_411rd"
solspec="$RAD_DATA/solar/cmip6_cycle23_sep96-dec08"

HITRAN_UV_O3="$RAD_DATA/gases/O3_110nm-1100nm.xsc"
o3_pt_file="$RAD_DATA/gases/pt_o3_uv"
ref_pt_file="$RAD_DATA/gases/ref_pt"

rm -f n.uvxsc
dat2xsc N.dat n.uvxsc
UV_N='n.uvxsc' # 0.04 - 102.7 nm

rm -f o.uvxsc
dat2xsc O.dat o.uvxsc
UV_O='o.uvxsc' # 0.04 - 102.7 nm

rm -f o2_hires.uvxsc
dat2xsc O2.dat o2_hires.uvxsc
UV_O2_HIRES='o2_hires.uvxsc' # 0.04 - 294 nm

rm -f n2_hires.uvxsc
dat2xsc N2.dat n2_hires.uvxsc
UV_N2_HIRES='n2_hires.uvxsc' # 0.04 - 102.7 nm

rm -f h2o_jpl.uvxsc
dat2xsc H2O.dat h2o_jpl.uvxsc
UV_H2O='h2o_jpl.uvxsc' #   7 - 198 nm

pt_file='pt_single'

# Create skeleton spectral file
mv ${specfile} ${specfile}_old 2> /dev/null
mv ${specfile}_k ${specfile}_old_k 2> /dev/null
prep_spec << EOF > prep_spec_skel_log
${specfile}
411
13
1
2
3
4
5
6
7
8
10
13
23
39
40
0
0
r
m 0.5E-9 411.5E-9 1.0E-9
0*411
0*411
n
2
n
${solspec}
n
3
a
-1
EOF


# Gases

# Water vapour (H2O)
if [ ! -s h2o_xuv_l ] || [ ! -s $SW_DATA/h2o_lbl_xuvrd.nc ] ; then
  echo 'H2O (XUV continuum)'
  rm -f h2o_xuv_l*
  Ccorr_k -F $pt_file -UVX $UV_H2O \
    -R 7 9 -i 1000.0 -l 1 1.0e-5 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o h2o_xuv_l -m h2o_xuv_lm -L $SW_DATA/h2o_lbl_xuvrd.nc -np $NUM_THREADS \
     > h2o_xuv_log
fi
if [ ! -s h2o_euv_l ] || [ ! -s $SW_DATA/h2o_lbl_euvrd.nc ] ; then
  echo 'H2O (EUV continuum)'
  rm -f h2o_euv_l*
  Ccorr_k -F $pt_file -UVX $UV_H2O \
    -R 10 99 -i 100.0 -l 1 1.0e-5 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o h2o_euv_l -m h2o_euv_lm -L $SW_DATA/h2o_lbl_euvrd.nc -np $NUM_THREADS \
     > h2o_euv_log
fi
if [ ! -s h2o_uv_l ] || [ ! -s $SW_DATA/h2o_lbl.nc ] ; then
  echo 'H2O (UV continuum)'
  rm -f h2o_uv_l*
  Ccorr_k -F $pt_file -UVX $UV_H2O \
    -R 100 198 -i 1.0 -l 1 1.0e-5 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o h2o_uv_l -m h2o_uv_lm -L $SW_DATA/h2o_lbl.nc -np $NUM_THREADS \
     > h2o_uv_log
fi

# Nitrogen (N2)
if [ ! -s n2_xuvhr_l ] || [ ! -s $SW_DATA/n2_lbl_xuvrd.nc ] ; then
  echo 'N2 (XUV continuum)'
  rm -f n2_xuvhr_l*
  Ccorr_k -F $pt_file -UVX $UV_N2_HIRES \
    -R 1 9 -i 1000.0 -l 13 7.5e3 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o n2_xuvhr_l -m n2_xuvhr_lm -L $SW_DATA/n2_lbl_xuvrd.nc -np $NUM_THREADS \
     > n2_xuvhr_log
fi
if [ ! -s n2_euvhr_l ] || [ ! -s $SW_DATA/n2_lbl_euvrd.nc ] ; then
  echo 'N2 (EUV continuum)'
  rm -f n2_euvhr_l*
  Ccorr_k -F $pt_file -UVX $UV_N2_HIRES \
    -R 10 99 -i 100.0 -l 13 7.5e3 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o n2_euvhr_l -m n2_euvhr_lm -L $SW_DATA/n2_lbl_euvrd.nc -np $NUM_THREADS \
     > n2_euvhr_log
fi

# Oxygen (O2)
if [ ! -s o2_xuvhr_l ] || [ ! -s $SW_DATA/o2_lbl_xuvrd.nc ] ; then
  echo 'O2 (XUV continuum)'
  rm -f o2_xuvhr_l*
  Ccorr_k -F $pt_file -UVX $UV_O2_HIRES \
    -R 1 9 -i 1000.0 -l 7 2.3e3 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o o2_xuvhr_l -m o2_xuvhr_lm -L $SW_DATA/o2_lbl_xuvrd.nc -np $NUM_THREADS \
     > o2_xuvhr_log
fi
if [ ! -s o2_euvhr_l ] || [ ! -s $SW_DATA/o2_lbl_euvrd.nc ] ; then
  echo 'O2 (EUV continuum)'
  rm -f o2_euvhr_l*
  Ccorr_k -F $pt_file -UVX $UV_O2_HIRES \
    -R 10 99 -i 100.0 -l 7 2.3e3 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o o2_euvhr_l -m o2_euvhr_lm -L $SW_DATA/o2_lbl_euvrd.nc -np $NUM_THREADS \
     > o2_euvhr_log
fi
if [ ! -s o2_uvhr_l ] || [ ! -s $SW_DATA/o2_lbl_uvhr.nc ] ; then
  echo 'O2 (UV continuum)'
  rm -f o2_uvhr_l*
  Ccorr_k -F $pt_file -UVX $UV_O2_HIRES \
    -R 100 293 -i 1.0 -l 7 2.3e3 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o o2_uvhr_l -m o2_uvhr_lm -L $SW_DATA/o2_lbl_uvhr.nc -np $NUM_THREADS \
     > o2_uvhr_log
fi

# Ozone (O3)
if [ ! -s o3_uvhr_l ] || [ ! -s $SW_DATA/o3_lbl_uvhr.nc ] ; then
  echo 'O3 (UV continuum)'
  rm -f o3_uvhr_l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R 111 411 -i 1.0 -l 3 1.0e-2 -t 1.0e-3  \
    -s $specfile +S $solspec -lk \
    -o o3_uvhr_l -m o3_uvhr_lm -L $SW_DATA/o3_lbl_uvhr.nc -np $NUM_THREADS \
     > o3_uvhr_log
fi

# Atomic Oxygen (O)
if [ ! -s o_xuvhr_l ] || [ ! -s $SW_DATA/o_lbl_xuvrd.nc ] ; then
  echo 'O (XUV continuum)'
  rm -f o_xuvhr_l*
  Ccorr_k -F $pt_file -UVX $UV_O \
    -R 1 9 -i 1000.0 -l 39 2.6e-4 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o o_xuvhr_l -m o_xuvhr_lm -L $SW_DATA/o_lbl_xuvrd.nc -np $NUM_THREADS \
     > o_xuvhr_log
fi
if [ ! -s o_euvhr_l ] || [ ! -s $SW_DATA/o_lbl_euvrd.nc ] ; then
  echo 'O (EUV continuum)'
  rm -f o_euvhr_l*
  Ccorr_k -F $pt_file -UVX $UV_O \
    -R 10 92 -i 100.0 -l 39 2.6e-4 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o o_euvhr_l -m o_euvhr_lm -L $SW_DATA/o_lbl_euvrd.nc -np $NUM_THREADS \
     > o_euvhr_log
fi

# Atomic Nitrogen (N)
if [ ! -s n_xuvhr_l ] || [ ! -s $SW_DATA/n_lbl_xuvrd.nc ] ; then
  echo 'N (XUV continuum)'
  rm -f n_xuvhr_l*
  Ccorr_k -F $pt_file -UVX $UV_N \
    -R 1 9 -i 1000.0 -l 40 3.0e-10 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o n_xuvhr_l -m n_xuvhr_lm -L $SW_DATA/n_lbl_xuvrd.nc -np $NUM_THREADS \
     > n_xuvhr_log
fi
if [ ! -s n_euvhr_l ] || [ ! -s $SW_DATA/n_lbl_euvrd.nc ] ; then
  echo 'N (EUV continuum)'
  rm -f n_euvhr_l*
  Ccorr_k -F $pt_file -UVX $UV_N \
    -R 10 87 -i 100.0 -l 40 3.0e-10 -t 1.0e-3  \
    -s $specfile +S $solspec \
    -o n_euvhr_l -m n_euvhr_lm -L $SW_DATA/n_lbl_euvrd.nc -np $NUM_THREADS \
     > n_euvhr_log
fi

# Construct spectral file
prep_spec << EOF > prep_spec_log1
${specfile}
a
5
o2_xuvhr_l
5
y
o2_euvhr_l
5
y
o2_uvhr_l
5
y
o3_uvhr_l
5
y
h2o_xuv_l
5
y
h2o_euv_l
5
y
h2o_uv_l
5
y
n2_xuvhr_l
5
y
n2_euvhr_l
5
y
o_xuvhr_l
5
y
o_euvhr_l
5
y
n_xuvhr_l
5
y
n_euvhr_l
-1
EOF

# Column ammounts integrated down to  stratopause  |  mesopause
# Column amount for Water Vapour      0.156458E-04    0.630611E-08
# Column amount for Carbon Dioxide    0.251123E-02    0.708379E-05
# Column amount for Ozone             0.784418E-05    0.128860E-07
# Column amount for Dinitrogen Oxide  0.138654E-07    0.103199E-10
# Column amount for Carbon monoxide   0.112071E-05    0.208955E-06
# Column amount for Methane           0.399384E-06    0.123864E-08
# Column amount for Oxygen            0.107215E+01    0.332647E-02
# Column amount for Nitrogen monoxide 0.834753E-07    0.249072E-07
# Column amount for Nitrogen dioxide  0.205777E-08    0.482538E-11
# Column amount for Nitrogen          0.351191E+01    0.130265E-01
# Column amount for Hydrogen          0.0             0.0
# Column amount for Atomic Oxygen     0.262064E-03    0.228072E-03
# Column amount for Atomic Nitrogen   0.299410E-09    0.260047E-09
tidy_90 <<EOF > tidy_log
${specfile}
o
6
0.630611E-08
0.708379E-05
0.128860E-07
0.103199E-10
0.208955E-06
0.123864E-08
0.332647E-02
0.249072E-07
0.482538E-11
0.130265E+00
0.0         
0.228072E-03
0.260047E-09
-1
EOF

prep_spec << EOF > prep_spec_log2
${specfile}
a
17
-1
${solspec}
a
0
0
0
20
7
1
n
O2_1.qy
O2_1.pe
20
y
7
2
n
O2_2.qy
O2_2.pe
20
y
7
6
n
O2_6.qy
O2_6.pe
20
y
7
7
n
O2_7.qy
O2_7.pe
20
y
13
1
n
N2_1.qy
N2_1.pe
20
y
13
2
n
N2_2.qy
N2_2.pe
20
y
13
3
n
N2_3.qy
N2_3.pe
20
y
39
1
n
O_1.qy
O_1.pe
20
y
39
2
n
O_2.qy
O_2.pe
20
y
39
3
n
O_3.qy
O_3.pe
20
y
39
4
n
O_4.qy
O_4.pe
20
y
39
5
n
O_5.qy
O_5.pe
20
y
40
1
n
N_1.qy
N_1.pe
20
y
1
2
n
H2O_2.qy

20
y
1
3
n
H2O_3.qy

20
y
1
5
n
H2O_5.qy

20
y
3
1
y
O3_Matsumi2002_1.qy

20
y
3
4
y
O3_Matsumi2002_4.qy

-1
EOF

exit 0
