#!/bin/bash

ierr=0

rm -f ch4_* co_* co2_* o2_* o3_* o_* n_* n2_* h2_* h2o_* n2o_* no2_* oh_*
rm -f *.uvxsc
rm -f sp_411nm sp_411nm_k
rm -f prep_spec_log1 prep_spec_log2 tidy_log prep_spec_skel_log

echo 'Creating sp_411nm spectral file'
./mk_sp_411nm
diff -q sp_411nm   sp_411nm_photol || ierr=1
diff -q sp_411nm_k sp_411nm_photol_k || ierr=1
if [ $ierr -gt 0 ] ; then
  exit 1
else
  echo 'sp_411nm OK'
  rm -f ch4_* co_* co2_* o2_* o3_* o_* n_* n2_* h2_* h2o_* n2o_* no2_* oh_*
  rm -f *.uvxsc
  rm -f sp_411nm sp_411nm_k
  rm -f prep_spec_log1 prep_spec_log2 tidy_log prep_spec_skel_log
  exit 0
fi
