# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 climt/ --count --show-source --statistics
    - name: Build climt
      run: |
           if [ "$RUNNER_OS" == "Linux" ]; then
            CLIMT_ARCH=Linux python setup.py develop
           elif [ "$RUNNER_OS"== "Windows" ]; then
            CLIMT_ARCH=Windows python setup.py develop 
           elif [ "$RUNNER_OS"== "macOS" ]; then
            CLIMT_ARCH=Darwin python setup.py develop
           else 
             echo "$RUNNER_OS not supported"
             exit 1
           fi
      shell: bash   
    - name: Test with pytest
      run:  |
       pytest
