# This workflow will install compilers and packges on windows platform

name: windows package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  windows_package:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: >- 
          gcc
          make
          gcc-fortran
          mingw-w64-openblas
    - run: gcc -v
    - run: gfortran -v
    - run: which gfortran 
