# This workflow will install compilers and packges on windows platform

name: windows package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  windows_package:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >- 
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-openblas
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.7"
    - name: Check Python
      shell: bash -l {0}
      run: |
        conda activate test
        which python
        echo $PATH
        which gcc
        which ld
        which gfortran
    - run: pacman -Ql mingw-w64-x86_64-gcc
    - run: pacman -Ql mingw-w64-x86_64-gcc-fortran
    - run: pacman -Ql mingw-w64-x86_64-openblas
    - run: pacman -Ql mingw-w64-x86_64-gcc-libgfortran
    - run: ls -l /mingw64/bin/
   # - run: export PATH=$( echo $pythonLocation| sed 's/\\/\//g'| sed 's/C:/\/c/' ):$PATH; echo $PATH
   # - run: |
  # PYPATH=$( echo $pythonLocation| sed 's/\\/\//g'| sed 's/C:/\/c/' )
  #  export PATH=$PYPATH:$PYPATH/Scripts/:$PATH; echo $PATH
    - shell: bash -l {0}
      run: |
          which gcc
          which ld
      #   python -m pip install -r requirements_dev.txt
      #    python setup.py develop
      #    py.test -v
      #    python setup.py bdist_wheel
